<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2022-06-08" />

<title>Cardiovascular diseases worsen the maternal prognosis of COVID-19</title>

<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/header-attrs-2.17/header-attrs.js"></script>
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/navigation-1.1/tabsets.js"></script>
<link href="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/highlightjs-9.12.0/highlight.js"></script>
<link href="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/pagedtable-1.1/js/pagedtable.js"></script>
<script src="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/kePrint-0.0.1/kePrint.js"></script>
<link href="Report-paper_COVID-19_cardiovascular-disease_revisão_PO_files/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Cardiovascular diseases worsen the maternal
prognosis of COVID-19</h1>
<h3 class="subtitle">Codes and outputs</h3>
<h4 class="date">06/08/2022</h4>

</div>


<div id="description" class="section level1">
<h1>Description</h1>
<p>This file presents the documentation of the analysis of article
“Cardiovascular diseases worsen the maternal prognosis of COVID-19” with
authors Carolina Testa, Luciana Godoi, Maria Rita Bortolotto, Nátaly
Monroy, Bruna de Mattos, Agatha Rodrigues, and Rossana Francisco.</p>
</div>
<div id="r-packages-used-functions-and-dataset-import"
class="section level1">
<h1>R packages used, functions and dataset import</h1>
<p>The data are analyzed using the free-software R (<a
href="https://www.R-project.org"
class="uri">https://www.R-project.org</a>) in version 4.0.3. Next, we
present and load the libraries used in the data analysis process.</p>
<pre class="r"><code>loadlibrary &lt;- function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = T)
    if (!require(x, character.only = TRUE))
      stop(&quot;Package not found&quot;)
  }
}

packages &lt;-
  c(
    &quot;dplyr&quot;,
    &quot;MatchIt&quot;,
    &quot;lubridate&quot;,
    &quot;readr&quot;,
    &quot;readxl&quot;,
    &quot;ggplot2&quot;,
    &quot;kableExtra&quot;,
    &quot;tables&quot;,
    &quot;questionr&quot;,
    &quot;car&quot;,
    &quot;data.table&quot;,
    &quot;magrittr&quot;,
    &quot;tidyverse&quot;,
    &quot;readxl&quot;,
    &quot;summarytools&quot;,
    &quot;modelsummary&quot;,
    &quot;RColorBrewer&quot;,
    &quot;zoo&quot;,
    &quot;WeightIt&quot;,
    &quot;jtools&quot;,
    &quot;cobalt&quot;,
    &quot;weights&quot;,
    &quot;psych&quot;
)
lapply(packages, loadlibrary)</code></pre>
<p>One can see below the functions that will be used in the data
analysis.</p>
<pre class="r"><code>#functions for summary measures
media &lt;- function(x)
  mean(x, na.rm = TRUE)
mediana &lt;- function(x)
  median(x, na.rm = TRUE)
DP &lt;- function(x)
  sd(x, na.rm = TRUE)
minimo &lt;- function(x)
  base::min(x, na.rm = TRUE)
maximo &lt;- function(x)
  base::max(x, na.rm = TRUE)
q25 &lt;- function(x)
  stats::quantile(x, p = 0.25, na.rm = TRUE)
q75 &lt;- function(x)
  stats::quantile(x, p = 0.75, na.rm = TRUE)
IQR &lt;- function(x)
  round(q75(x) - q25(x), 2)
n &lt;- function(x)
  sum(!is.na(x))</code></pre>
<p>The Influenza Epidemiological Surveillance Information System,
SIVEP-Gripe (Sistema de Informação de Vigilância Epidemiológica da
Gripe), is a nationwide surveillance database used to monitor severe
acute respiratory infections in Brazil.</p>
<p>Notification is mandatory for Influenza Syndrome (characterized by at
least two of the following signs and symptoms: fever, even if referred,
chills, sore throat, headache, cough, runny nose, olfactory or taste
disorders) and who has dyspnea/respiratory discomfort or persistent
pressure in the chest or O2 saturation less than 95% in room air or
bluish color of the lips or face. Asymptomatic individuals with
laboratory confirmation by molecular biology or immunological
examination for COVID-19 infection are also reported.</p>
<p>For notifications in Sivep-Gripe, hospitalized cases in both public
and private hospitals and all deaths due to severe acute respiratory
infections regardless of hospitalization must be considered.</p>
<p>The search was limited to the first notified case of COVID-19 in
February 2020 until the 15th epidemiological week of 2021 (up to April
17, 2021). The datasets were obtained on May 5, 2021, on the site <a
href="https://opendatasus.saude.gov.br/dataset"
class="uri">https://opendatasus.saude.gov.br/dataset</a>. The first
period (8th to 53rd epidemiological week of 2020) and the second period
(1st to 15th epidemiological week of 2021) datasets can be obtained at
<a
href="https://drive.google.com/file/d/1jts4h0ovdwFh86SdKyslMLSG9rOy3UjX/view?usp=sharing"
class="uri">https://drive.google.com/file/d/1jts4h0ovdwFh86SdKyslMLSG9rOy3UjX/view?usp=sharing</a>
and at <a
href="https://drive.google.com/file/d/1gQSy_dcUkd1UrDEcsrDbyGl4gEvcI8z_/view?usp=sharing"
class="uri">https://drive.google.com/file/d/1gQSy_dcUkd1UrDEcsrDbyGl4gEvcI8z_/view?usp=sharing</a>,
respectively. The data are loaded below:</p>
<pre class="r"><code>######### loading the datasets ###########
#2021
data_2021 &lt;- read_delim(
  &quot;INFLUD21-03-05-2021.csv&quot;,
  &quot;;&quot;,
  escape_double = FALSE,
  locale = locale(encoding = &quot;ISO-8859-2&quot;),
  trim_ws = TRUE
)


#2020
data_2020 &lt;- read_delim(
  &quot;INFLUD-03-05-2021.csv&quot;,
  &quot;;&quot;,
  escape_double = FALSE,
  locale = locale(encoding = &quot;ISO-8859-2&quot;),
  trim_ws = TRUE
)


sem &lt;- 15 #limit of epidemiological week of 2021

#memory.limit(999999)

#### Concatenating 2020 and 2021 data ##############
data_all &lt;- rbind(data_2020, data_2021)

#Creating the case year variable
data_all &lt;-  data_all %&gt;%
  dplyr::mutate(
    dt_sint = as.Date(DT_SIN_PRI, format = &quot;%d/%m/%Y&quot;),
    year_case = lubridate::year(dt_sint),
  )</code></pre>
<p>There are 1905854 observations. The case selection is presented in
the following according to the flowchart presented in the article.</p>
</div>
<div id="case-selection-and-data-treatment" class="section level1">
<h1>Case selection and data treatment</h1>
<p>The first filter consists of selecting the cases from 8th
epidemiological week of 2020 to 15th epidemiological week of 2021.</p>
<pre class="r"><code>#Cases from the 8th epidemiological week of 2020 to 15th of 2021
data1 &lt;- data_all %&gt;% 
  filter((year_case==2020 &amp; SEM_PRI &gt;=8) | year_case ==2021)</code></pre>
<p>There are 12563 cases in 2021 in epidemiological week 53 of 2020.
These are cases from the first two days of 2021, which are still part of
the last epidemiological week of 2020 (<a
href="http://portalsinan.saude.gov.br/calendario-epidemiologico?layout=edit&amp;id=168"
class="uri">http://portalsinan.saude.gov.br/calendario-epidemiologico?layout=edit&amp;id=168</a>).
However, these cases belong to the 53rd week of 2020 and we corrected as
follows:</p>
<pre class="r"><code>  data1 &lt;- data1 %&gt;% 
  mutate(year_case = ifelse(year_case ==2021 &amp; SEM_PRI ==53, 2020, year_case)) %&gt;%  
  filter(year_case==2020 | (year_case ==2021 &amp; SEM_PRI &lt;= sem))</code></pre>
<p>There are 1876953 observations.</p>
<p>The next selection consists of selecting only confirmed cases of
COVID-19:</p>
<pre class="r"><code>##Filtering confirmed cases of COVID-19  
data2 &lt;- data1 %&gt;% 
    filter(CLASSI_FIN == 5)</code></pre>
<p>There are 1174350 observations.</p>
<pre class="r"><code>with(data2, table(PCR_SARS2, CRITERIO))</code></pre>
<pre><code>##          CRITERIO
## PCR_SARS2      1      2      3      4
##         1 755241   1546   2607   1344</code></pre>
<p>The next step is to identify hospitalized cases
(<code>HOSPITAL=1</code>) and then select only those cases.</p>
<pre class="r"><code>#Filtering only hospitalized cases
data3 &lt;- data2 %&gt;% 
  filter(HOSPITAL == 1)</code></pre>
<p>Now we have 1114042 observations.</p>
<p>The next selection consists of selecting females cases:</p>
<pre class="r"><code>##Filtering female notifications
data4 &lt;- filter(data3, CS_SEXO == &quot;F&quot;)</code></pre>
<p>There are 495698 observations.</p>
<p>The next selection consists of selecting women between 10 and 55
years old.</p>
<pre class="r"><code>#Filtering women aged 10-55
data5 &lt;- data4 %&gt;% 
  filter(NU_IDADE_N &gt; 9 &amp; NU_IDADE_N &lt;= 55)</code></pre>
<p>There are 174525 observations.</p>
<p>The next step is to identify pregnant and postpartum people (variable
<code>classi_gesta_puerp</code>) and then select only those cases.</p>
<pre class="r"><code>#Creating the classification variable if pregnant, postpartum and not (neither pregnant nor postpartum)
data5 &lt;- data5 %&gt;%
  mutate(
    classi_gesta_puerp = case_when(
      CS_GESTANT == 1  ~ &quot;1tri&quot;,  #1st trimester
      CS_GESTANT == 2  ~ &quot;2tri&quot;,  #2nd trimester
      CS_GESTANT == 3  ~ &quot;3tri&quot;,  #3rd trimester
      CS_GESTANT == 4  ~ &quot;IG_ig&quot;, #ignored gestational Age
      CS_GESTANT == 5 &amp;
        PUERPERA == 1 ~ &quot;puerp&quot;,  #puerperium
      CS_GESTANT == 9 &amp; PUERPERA == 1 ~ &quot;puerp&quot;, #puerperium
      TRUE ~ &quot;no&quot; #neither pregnant nor postpartum
    )
  )

#Filtering only pregnant and postpartum women
data6 &lt;- data5 %&gt;%
  filter(classi_gesta_puerp != &quot;no&quot;)</code></pre>
<p>There are 10635 observations.</p>
<p>The variable identified as <code>EVOLUCAO</code> is categorized with
1 - cure, 2 - death by SARS, 3 - death by other cause, 9 - ignored.</p>
<pre class="r"><code>with(data6, freq(EVOLUCAO))</code></pre>
<pre><code>## Frequencies  
## data6$EVOLUCAO  
## Type: Numeric  
## 
##                Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------- --------- -------------- --------- --------------
##           1    8005     85.38          85.38     75.27          75.27
##           2     979     10.44          95.82      9.21          84.48
##           3      15      0.16          95.98      0.14          84.62
##           9     377      4.02         100.00      3.54          88.16
##        &lt;NA&gt;    1259                              11.84         100.00
##       Total   10635    100.00         100.00    100.00         100.00</code></pre>
<p>Now we are going to select only the finalized cases:</p>
<pre class="r"><code>#Filtering only finalized cases
data7 &lt;- data6 %&gt;% 
  filter((EVOLUCAO == 1 | EVOLUCAO == 2 | EVOLUCAO == 3) &amp; !is.na(EVOLUCAO))

#Creating the evolution variable  
data7 &lt;- data7 %&gt;% 
  mutate(evolution = case_when(
    EVOLUCAO == 1 ~ &quot;cure&quot;, 
    EVOLUCAO == 2 ~ &quot;death&quot;,
    EVOLUCAO == 3 ~ &quot;death&quot;
  ))

with(data7, freq(evolution))</code></pre>
<pre><code>## Frequencies  
## data7$evolution  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##        cure   8005     88.95          88.95     88.95          88.95
##       death    994     11.05         100.00     11.05         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total   8999    100.00         100.00    100.00         100.00</code></pre>
<p>There are 8999 confirmed and hospitalized cases of COVID-19 in
pregnant and postpartum women aged 10 to 55 years. We identify 60.42% of
these notifications without any information about the presence or
absence of cardiovascular diseases (CVD). The next selection consists of
selecting cases where the CVD variable (<code>CARDIOPATI</code>)
indicates yes or no:</p>
<pre class="r"><code>with(data7, freq(CARDIOPATI))</code></pre>
<pre><code>## Frequencies  
## data7$CARDIOPATI  
## Type: Numeric  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           1    602     16.55          16.55      6.69           6.69
##           2   2960     81.39          97.94     32.89          39.58
##           9     75      2.06         100.00      0.83          40.42
##        &lt;NA&gt;   5362                              59.58         100.00
##       Total   8999    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>#Creating the CVD variable
data7 &lt;- data7 %&gt;% 
  mutate(CVD = case_when(
    CARDIOPATI == 1 ~ &quot;yes&quot;, 
    CARDIOPATI == 2 ~ &quot;no&quot;,
    TRUE ~ NA_character_
  ))</code></pre>
<p>Now we present the final dataset.</p>
<pre class="r"><code>#Filtering cases with information about CVD
data &lt;- data7 %&gt;% 
  filter(!is.na(CVD))</code></pre>
<pre class="r"><code>questionr::freq(
  data$CVD,
  cum = FALSE,
  total = TRUE,
  na.last = FALSE,
  valid = FALSE
)  %&gt;%
  kable(caption = &quot;Frequency of CVD&quot;, digits = 2)  %&gt;%
  kable_styling(latex_options = &quot;HOLD_position&quot;)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Frequency of CVD
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
%
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
2960
</td>
<td style="text-align:right;">
83.1
</td>
</tr>
<tr>
<td style="text-align:left;">
yes
</td>
<td style="text-align:right;">
602
</td>
<td style="text-align:right;">
16.9
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
3562
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>data7 &lt;- data7 %&gt;%
    mutate(pcr_covid_SN = case_when(
        (PCR_SARS2 == 1) |
            (
                str_detect(DS_PCR_OUT, &quot;COVID|COVID 19|COVID-19&quot;)
            ) ~ &quot;yes&quot;, 
        TRUE ~ &quot;no&quot; 
    ))

data7 &lt;- data7 %&gt;%
    mutate(ant_covid_SN = case_when(
        (AN_SARS2 == 1 &amp; pcr_covid_SN != &quot;yes&quot;) |
            (pcr_covid_SN != &quot;yes&quot; &amp;
                str_detect(DS_AN_OUT, &quot;COVID|COVID 19|COVID  19|COVID-19|COVID19|SARS COV 2|SARS COV-2|SARS COV2|
                           SARS COVID 19|SARS-COV-2|SARS-COV2|SARS-COV2 - TESTE RAPIDO|SARS-COVID2|SARSCOV2|
                           TR COVID IGM +&quot;)
            ) ~ &quot;yes&quot;, 
        TRUE ~ &quot;no&quot; 
    ))

data7 &lt;- data7 %&gt;%
    mutate(soro_SN = case_when(
      ((RES_IGG == 1 | RES_IGM == 1 | RES_IGA == 1) &amp; (pcr_covid_SN != &quot;yes&quot;) &amp; (ant_covid_SN != &quot;yes&quot;) 
            ) ~ &quot;yes&quot;, 
        TRUE ~ &quot;no&quot; 
    ))

data &lt;- data7 %&gt;% 
  filter(!is.na(CVD))</code></pre>
<p>The variable <code>CRITERIO</code> presents the criterion used for
the final classification of the case, 1 - laboratory, 2 - clinical
epidemiological, 3 - clinical and 4 - clinical by image (chest
x-ray/tomography).</p>
<pre class="r"><code>table(data$CRITERIO, useNA=&quot;ifany&quot;)</code></pre>
<pre><code>## 
##    1    2    3    4 &lt;NA&gt; 
## 3327   16   51  128   40</code></pre>
<p>We note that some observations with the variable
<code>CRITERIO</code> as 2 - clinical epidemiological, 3 - clinical and
4 - clinical by image (chest x-ray/tomography) or empty cell had
positive laboratory results. To evaluate this cases, we conssidered a
new variable named as <code>Final_criterion</code>.</p>
<pre class="r"><code>data$Final_criterion &lt;- data$CRITERIO

a2 &lt;-  which(data$CRITERIO==2 &amp; (data$soro_SN == &quot;yes&quot; | data$ant_covid_SN == &quot;yes&quot; | data$pcr_covid_SN == &quot;yes&quot;))
data$Final_criterion[a2] &lt;- 1

a3 &lt;-  which(data$CRITERIO==3 &amp; (data$soro_SN == &quot;yes&quot; | data$ant_covid_SN == &quot;yes&quot; | data$pcr_covid_SN == &quot;yes&quot;))
data$Final_criterion[a3] &lt;- 1

a4 &lt;-  which(data$CRITERIO==4 &amp; (data$soro_SN == &quot;yes&quot; | data$ant_covid_SN == &quot;yes&quot; | data$pcr_covid_SN == &quot;yes&quot;))
data$Final_criterion[a4] &lt;- 1

a &lt;-  which(is.na(data$CRITERIO) &amp; (data$soro_SN == &quot;yes&quot; | data$ant_covid_SN == &quot;yes&quot; | data$pcr_covid_SN == &quot;yes&quot;))
data$Final_criterion[a] &lt;- 1

table(data$Final_criterion, useNA=&quot;ifany&quot;)</code></pre>
<pre><code>## 
##    1    2    3    4 &lt;NA&gt; 
## 3381    8   36  126   11</code></pre>
<pre class="r"><code>round(prop.table(table(data$Final_criterion, useNA=&quot;ifany&quot;))*100, 2)</code></pre>
<pre><code>## 
##     1     2     3     4  &lt;NA&gt; 
## 94.92  0.22  1.01  3.54  0.31</code></pre>
<p>These 0.31% cases of NA’s corresponds to observations waiting the
results of laboratory tests or observations with positive results of
RT-PCR and/or antigen test without specification for COVID-19 or any
other virus. Of the 126 observations with criteria defined by imaging,
54 (42.86%) of them are awaiting laboratory results
(<code>RES_AN</code>== 5 and <code>PCR_RESUL</code> == 5).</p>
</div>
<div id="epidemiologic-characteristics" class="section level1">
<h1># Epidemiologic characteristics</h1>
<div id="ethnicity" class="section level2">
<h2>Ethnicity</h2>
<pre class="r"><code># Ethnicity
data &lt;-  data %&gt;%
  mutate(
    ethnicity = case_when(
      CS_RACA == 1 ~ &quot;white&quot;,
      CS_RACA == 2 ~ &quot;black&quot;,
      CS_RACA == 3 ~ &quot;yellow&quot;,
      CS_RACA == 4 ~ &quot;brown&quot;,
      CS_RACA == 5 ~ &quot;indigenous&quot;,
      TRUE ~ NA_character_
    )
  )</code></pre>
<pre class="r"><code>with(data, ctable(ethnicity, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## ethnicity * CVD  
## Data Frame: data  
## 
## ------------ ----- --------------- -------------- ---------------
##                CVD              no            yes           Total
##    ethnicity                                                     
##        black          167 (  6.5%)    46 (  9.1%)    213 (  6.9%)
##        brown         1375 ( 53.5%)   244 ( 48.1%)   1619 ( 52.6%)
##   indigenous           30 (  1.2%)     1 (  0.2%)     31 (  1.0%)
##        white          975 ( 37.9%)   214 ( 42.2%)   1189 ( 38.6%)
##       yellow           24 (  0.9%)     2 (  0.4%)     26 (  0.8%)
##        Total         2571 (100.0%)   507 (100.0%)   3078 (100.0%)
## ------------ ----- --------------- -------------- ---------------</code></pre>
<pre class="r"><code>fisher.test(data$ethnicity, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$ethnicity and data$CVD
## p-value = 0.007096
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="education" class="section level2">
<h2>Education</h2>
<pre class="r"><code>data &lt;- data %&gt;%
     mutate(education = case_when(CS_ESCOL_N == 0 ~ &quot;No schooling&quot;,
                        CS_ESCOL_N == 1 ~ &quot;1st to 5th grade&quot;,
                        CS_ESCOL_N == 2 ~ &quot;6th to 9th grade&quot;,
                        CS_ESCOL_N == 3 ~ &quot;Middle school&quot;,
                        CS_ESCOL_N == 4 ~ &quot;Superior&quot;,
                          TRUE ~ NA_character_))

data$education &lt;- factor(data$education,
levels = c(&quot;No schooling&quot;,&quot;1st to 5th grade&quot;, &quot;6th to 9th grade&quot;,
&quot;Middle school&quot;, &quot;Superior&quot;))</code></pre>
<pre class="r"><code>with(data, ctable(education, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## education * CVD  
## Data Frame: data  
## 
## ------------------ ----- --------------- -------------- ---------------
##                      CVD              no            yes           Total
##          education                                                     
##       No schooling           11 (  0.7%)     2 (  0.7%)     13 (  0.7%)
##   1st to 5th grade          123 (  7.9%)    33 ( 12.2%)    156 (  8.5%)
##   6th to 9th grade          307 ( 19.7%)    52 ( 19.2%)    359 ( 19.6%)
##      Middle school          857 ( 55.0%)   140 ( 51.7%)    997 ( 54.5%)
##           Superior          260 ( 16.7%)    44 ( 16.2%)    304 ( 16.6%)
##              Total         1558 (100.0%)   271 (100.0%)   1829 (100.0%)
## ------------------ ----- --------------- -------------- ---------------</code></pre>
<pre class="r"><code>fisher.test(data$education, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$education and data$CVD
## p-value = 0.2405
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="age-years" class="section level2">
<h2>Age (Years)</h2>
<pre class="r"><code>datasummary((CVD) ~ NU_IDADE_N*(n+media+DP+mediana+minimo+maximo+q25+q75+IQR),
            data = data, output = &#39;markdown&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">CVD</th>
<th align="right">n</th>
<th align="right">media</th>
<th align="right">DP</th>
<th align="right">mediana</th>
<th align="right">minimo</th>
<th align="right">maximo</th>
<th align="right">q25</th>
<th align="right">q75</th>
<th align="right">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">2960</td>
<td align="right">30.00</td>
<td align="right">7.43</td>
<td align="right">30.00</td>
<td align="right">13.00</td>
<td align="right">55.00</td>
<td align="right">24.00</td>
<td align="right">35.00</td>
<td align="right">11.00</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">602</td>
<td align="right">34.76</td>
<td align="right">8.52</td>
<td align="right">34.00</td>
<td align="right">15.00</td>
<td align="right">55.00</td>
<td align="right">29.00</td>
<td align="right">39.75</td>
<td align="right">10.75</td>
</tr>
</tbody>
</table>
<pre class="r"><code>t.test(NU_IDADE_N ~ CVD, data = data)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  NU_IDADE_N by CVD
## t = -12.745, df = 797.4, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -5.485124 -4.021042
## sample estimates:
##  mean in group no mean in group yes 
##          30.00439          34.75748</code></pre>
</div>
<div id="age-group" class="section level2">
<h2>Age group</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(
    age_group = case_when(
      NU_IDADE_N &lt;= 19 ~ &quot;&lt;20&quot;,
      NU_IDADE_N &gt;= 20
      &amp; NU_IDADE_N &lt;= 34 ~ &quot;20-34&quot;,
      NU_IDADE_N &gt; 34 ~ &quot;&gt;=35&quot;,
      TRUE ~ NA_character_
    )
  )
data$age_group &lt;-
  factor(data$age_group, levels = c(&quot;&lt;20&quot;, &quot;20-34&quot;, &quot;&gt;=35&quot;))</code></pre>
<pre class="r"><code>with(data, ctable(age_group, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## age_group * CVD  
## Data Frame: data  
## 
## ----------- ----- --------------- -------------- ---------------
##               CVD              no            yes           Total
##   age_group                                                     
##         &lt;20          237 (  8.0%)    10 (  1.7%)    247 (  6.9%)
##       20-34         1895 ( 64.0%)   292 ( 48.5%)   2187 ( 61.4%)
##        &gt;=35          828 ( 28.0%)   300 ( 49.8%)   1128 ( 31.7%)
##       Total         2960 (100.0%)   602 (100.0%)   3562 (100.0%)
## ----------- ----- --------------- -------------- ---------------</code></pre>
<pre class="r"><code>with(data,fisher.test(age_group, CVD))</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  age_group and CVD
## p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
<p>Now we consider a new grouping for the age variable by analyzing
adolescents in more detail.</p>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(
    age_group2 = case_when(
      NU_IDADE_N &lt;= 13 ~ &quot;&lt;14&quot;,
      NU_IDADE_N &lt;= 18 &amp; NU_IDADE_N &lt;= 14  ~ &quot;14-18&quot;,
      NU_IDADE_N &gt; 18
      &amp; NU_IDADE_N &lt;= 34 ~ &quot;19-34&quot;,
      NU_IDADE_N &gt; 34 ~ &quot;&gt;=35&quot;,
      TRUE ~ NA_character_
    )
  )
data$age_group2 &lt;-
  factor(data$age_group2, levels = c(&quot;&lt;14&quot;, &quot;14-18&quot;, &quot;19-34&quot;, &quot;&gt;=35&quot;))</code></pre>
<pre class="r"><code>with(data, ctable(age_group2, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## age_group2 * CVD  
## Data Frame: data  
## 
## ------------ ----- ---------------- -------------- ----------------
##                CVD               no            yes            Total
##   age_group2                                                       
##          &lt;14            1 (  0.04%)     0 (  0.0%)      1 (  0.03%)
##        14-18            9 (  0.32%)     0 (  0.0%)      9 (  0.26%)
##        19-34         1970 ( 70.16%)   300 ( 50.0%)   2270 ( 66.61%)
##         &gt;=35          828 ( 29.49%)   300 ( 50.0%)   1128 ( 33.10%)
##        Total         2808 (100.00%)   600 (100.0%)   3408 (100.00%)
## ------------ ----- ---------------- -------------- ----------------</code></pre>
<pre class="r"><code>with(data,fisher.test(age_group2, CVD))</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  age_group2 and CVD
## p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="residence-area" class="section level2">
<h2>Residence area</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(zone = case_when(CS_ZONA ==1  ~ &quot;Urban&quot;,
                             CS_ZONA == 2 ~ &quot;Rural&quot;,
                             CS_ZONA == 3 ~ &quot;Periurban&quot;,
                               TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable( zone, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## zone * CVD  
## Data Frame: data  
## 
## ----------- ----- --------------- -------------- ---------------
##               CVD              no            yes           Total
##        zone                                                     
##   Periurban           10 (  0.4%)     3 (  0.5%)     13 (  0.4%)
##       Rural          159 (  5.7%)    24 (  4.4%)    183 (  5.5%)
##       Urban         2618 ( 93.9%)   522 ( 95.1%)   3140 ( 94.1%)
##       Total         2787 (100.0%)   549 (100.0%)   3336 (100.0%)
## ----------- ----- --------------- -------------- ---------------</code></pre>
<pre class="r"><code>fisher.test(data$zone, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$zone and data$CVD
## p-value = 0.3673
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="gestational-moment" class="section level2">
<h2>Gestational moment</h2>
<pre class="r"><code>ctable(data$classi_gesta_puerp, data$CVD, prop=&quot;c&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE)</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## classi_gesta_puerp * CVD  
## Data Frame: data  
## 
## 
## -------------------- ----- --------------- -------------- ---------------
##                        CVD              no            yes           Total
##   classi_gesta_puerp                                                     
##                 1tri          161 (  5.4%)    34 (  5.6%)    195 (  5.5%)
##                 2tri          471 ( 15.9%)   120 ( 19.9%)    591 ( 16.6%)
##                 3tri         1199 ( 40.5%)   248 ( 41.2%)   1447 ( 40.6%)
##                IG_ig           84 (  2.8%)    30 (  5.0%)    114 (  3.2%)
##                puerp         1045 ( 35.3%)   170 ( 28.2%)   1215 ( 34.1%)
##                Total         2960 (100.0%)   602 (100.0%)   3562 (100.0%)
## -------------------- ----- --------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    19.4898     4     6e-04  
## ----------------------------</code></pre>
</div>
<div id="hospital-acquired-infection" class="section level2">
<h2>Hospital-acquired infection</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(hospital_infection = case_when(NOSOCOMIAL ==1  ~ &quot;yes&quot;,
                             NOSOCOMIAL == 2 ~ &quot;no&quot;,
                               TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable( hospital_infection, CVD, prop = &quot;c&quot;, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## hospital_infection * CVD  
## Data Frame: data  
## 
## -------------------- ----- --------------- -------------- ---------------
##                        CVD              no            yes           Total
##   hospital_infection                                                     
##                   no         2551 ( 98.0%)   448 ( 98.0%)   2999 ( 98.0%)
##                  yes           53 (  2.0%)     9 (  2.0%)     62 (  2.0%)
##                Total         2604 (100.0%)   457 (100.0%)   3061 (100.0%)
## -------------------- ----- --------------- -------------- ---------------</code></pre>
<pre class="r"><code>fisher.test(data$hospital_infection, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$hospital_infection and data$CVD
## p-value = 1
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.4163122 1.9955578
## sample estimates:
## odds ratio 
##  0.9669453</code></pre>
</div>
</div>
<div id="symptoms" class="section level1">
<h1>Symptoms</h1>
<div id="fever" class="section level2">
<h2>Fever</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(fever = case_when(FEBRE == 1 ~ &quot;yes&quot;,
                              FEBRE == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, fever, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * fever  
## Data Frame: data  
## 
## 
## ------- ------- -------------- -------------- ---------------
##           fever             no            yes           Total
##     CVD                                                      
##      no           1289 (44.2%)   1625 (55.8%)   2914 (100.0%)
##     yes            209 (38.3%)    337 (61.7%)    546 (100.0%)
##   Total           1498 (43.3%)   1962 (56.7%)   3460 (100.0%)
## ------- ------- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    6.4048      1    0.0114  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.28        1.06       1.54   
## ----------------------------------</code></pre>
</div>
<div id="cough" class="section level2">
<h2>Cough</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(cough = case_when(TOSSE == 1 ~ &quot;yes&quot;,
                              TOSSE == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, cough, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * cough  
## Data Frame: data  
## 
## 
## ------- ------- -------------- -------------- ---------------
##           cough             no            yes           Total
##     CVD                                                      
##      no           1002 (34.4%)   1913 (65.6%)   2915 (100.0%)
##     yes            138 (24.6%)    424 (75.4%)    562 (100.0%)
##   Total           1140 (32.8%)   2337 (67.2%)   3477 (100.0%)
## ------- ------- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    20.1693     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.61        1.31       1.98   
## ----------------------------------</code></pre>
</div>
<div id="sore-throat" class="section level2">
<h2>Sore throat</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(sore_throat = case_when(GARGANTA == 1 ~ &quot;yes&quot;,
                              GARGANTA  == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, sore_throat, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * sore_throat  
## Data Frame: data  
## 
## 
## ------- ------------- -------------- ------------- ---------------
##           sore_throat             no           yes           Total
##     CVD                                                           
##      no                 2245 (78.5%)   616 (21.5%)   2861 (100.0%)
##     yes                  367 (74.7%)   124 (25.3%)    491 (100.0%)
##   Total                 2612 (77.9%)   740 (22.1%)   3352 (100.0%)
## ------- ------------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.1648      1    0.0752  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.23        0.99       1.54   
## ----------------------------------</code></pre>
</div>
<div id="dyspnea" class="section level2">
<h2>Dyspnea</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(dyspnea = case_when(DISPNEIA == 1 ~ &quot;yes&quot;,
                              DISPNEIA == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, dyspnea, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * dyspnea  
## Data Frame: data  
## 
## 
## ------- --------- -------------- -------------- ---------------
##           dyspnea             no            yes           Total
##     CVD                                                        
##      no             1361 (46.7%)   1553 (53.3%)   2914 (100.0%)
##     yes              154 (27.7%)    401 (72.3%)    555 (100.0%)
##   Total             1515 (43.7%)   1954 (56.3%)   3469 (100.0%)
## ------- --------- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    67.3439     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.28        1.87       2.79   
## ----------------------------------</code></pre>
</div>
<div id="respiratory-distress" class="section level2">
<h2>Respiratory distress</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(resp_dist = case_when(DESC_RESP == 1 ~ &quot;yes&quot;,
                              DESC_RESP == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, resp_dist, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * resp_dist  
## Data Frame: data  
## 
## 
## ------- ----------- -------------- -------------- ---------------
##           resp_dist             no            yes           Total
##     CVD                                                          
##      no               1541 (53.1%)   1361 (46.9%)   2902 (100.0%)
##     yes                213 (40.3%)    316 (59.7%)    529 (100.0%)
##   Total               1754 (51.1%)   1677 (48.9%)   3431 (100.0%)
## ------- ----------- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    28.9948     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.68        1.39       2.03   
## ----------------------------------</code></pre>
</div>
<div id="saturation" class="section level2">
<h2>Saturation</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(saturation = case_when(SATURACAO == 1 ~ &quot;yes&quot;,
                              SATURACAO == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, saturation, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * saturation  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- -------------- ---------------
##           saturation             no            yes           Total
##     CVD                                                           
##      no                1873 (65.1%)   1003 (34.9%)   2876 (100.0%)
##     yes                 231 (43.4%)    301 (56.6%)    532 (100.0%)
##   Total                2104 (61.7%)   1304 (38.3%)   3408 (100.0%)
## ------- ------------ -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    88.612      1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.43        2.02       2.94   
## ----------------------------------</code></pre>
</div>
<div id="diarrhea" class="section level2">
<h2>Diarrhea</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(diarrhea = case_when(DIARREIA == 1 ~ &quot;yes&quot;,
                              DIARREIA == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, diarrhea, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * diarrhea  
## Data Frame: data  
## 
## 
## ------- ---------- -------------- ------------- ---------------
##           diarrhea             no           yes           Total
##     CVD                                                        
##      no              2557 (88.8%)   324 (11.2%)   2881 (100.0%)
##     yes               421 (87.0%)    63 (13.0%)    484 (100.0%)
##   Total              2978 (88.5%)   387 (11.5%)   3365 (100.0%)
## ------- ---------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.1081      1    0.2925  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.18        0.88       1.58   
## ----------------------------------</code></pre>
</div>
<div id="vomit" class="section level2">
<h2>Vomit</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(vomit = case_when(VOMITO == 1 ~ &quot;yes&quot;,
                              VOMITO == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, vomit, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * vomit  
## Data Frame: data  
## 
## 
## ------- ------- -------------- ------------- ---------------
##           vomit             no           yes           Total
##     CVD                                                     
##      no           2589 (90.2%)   282 ( 9.8%)   2871 (100.0%)
##     yes            423 (87.9%)    58 (12.1%)    481 (100.0%)
##   Total           3012 (89.9%)   340 (10.1%)   3352 (100.0%)
## ------- ------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##     2.021      1    0.1551  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.26        0.93       1.70   
## ----------------------------------</code></pre>
</div>
<div id="abdominal-pain" class="section level2">
<h2>Abdominal pain</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(abd_pain = case_when(DOR_ABD == 1 ~ &quot;yes&quot;,
                              DOR_ABD == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, abd_pain, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * abd_pain  
## Data Frame: data  
## 
## 
## ------- ---------- -------------- ------------- ---------------
##           abd_pain             no           yes           Total
##     CVD                                                        
##      no              1877 (91.1%)   183 ( 8.9%)   2060 (100.0%)
##     yes               291 (89.0%)    36 (11.0%)    327 (100.0%)
##   Total              2168 (90.8%)   219 ( 9.2%)   2387 (100.0%)
## ------- ---------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.2858      1    0.2568  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.27        0.87       1.85   
## ----------------------------------</code></pre>
</div>
<div id="fatigue" class="section level2">
<h2>Fatigue</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(fatigue = case_when(FADIGA == 1 ~ &quot;yes&quot;,
                              FADIGA == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, fatigue, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * fatigue  
## Data Frame: data  
## 
## 
## ------- --------- -------------- ------------- ---------------
##           fatigue             no           yes           Total
##     CVD                                                       
##      no             1609 (77.8%)   460 (22.2%)   2069 (100.0%)
##     yes              238 (69.6%)   104 (30.4%)    342 (100.0%)
##   Total             1847 (76.6%)   564 (23.4%)   2411 (100.0%)
## ------- --------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    10.4972     1    0.0012  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.53        1.19       1.97   
## ----------------------------------</code></pre>
</div>
<div id="loss-of-smell" class="section level2">
<h2>Loss of smell</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(loss_smell = case_when(PERD_OLFT == 1 ~ &quot;yes&quot;,
                              PERD_OLFT == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, loss_smell, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * loss_smell  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- ------------- ---------------
##           loss_smell             no           yes           Total
##     CVD                                                          
##      no                1683 (81.4%)   384 (18.6%)   2067 (100.0%)
##     yes                 250 (74.2%)    87 (25.8%)    337 (100.0%)
##   Total                1933 (80.4%)   471 (19.6%)   2404 (100.0%)
## ------- ------------ -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    9.1828      1    0.0024  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.53        1.17       1.99   
## ----------------------------------</code></pre>
</div>
<div id="loss-of-taste" class="section level2">
<h2>Loss of taste</h2>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(loss_taste = case_when(PERD_PALA == 1 ~ &quot;yes&quot;,
                              PERD_PALA == 2 ~ &quot;no&quot;,
                              TRUE ~ NA_character_))</code></pre>
<pre class="r"><code>with(data, ctable(CVD, loss_taste, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * loss_taste  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- ------------- ---------------
##           loss_taste             no           yes           Total
##     CVD                                                          
##      no                1694 (82.1%)   369 (17.9%)   2063 (100.0%)
##     yes                 250 (74.0%)    88 (26.0%)    338 (100.0%)
##   Total                1944 (81.0%)   457 (19.0%)   2401 (100.0%)
## ------- ------------ -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    11.9908     1     5e-04  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.62        1.24       2.11   
## ----------------------------------</code></pre>
</div>
<div id="any-respiratory-symptom" class="section level2">
<h2>Any respiratory symptom</h2>
<p>Now we are going to create the variable <code>resp_symp</code>
indicating the presence of at least one respiratory symptom (Dyspnea,
Fadigue, Saturation, Respiratory distress). Empty cells are considered
missing data (<code>&lt;NA&gt;</code>). The variable
<code>qt_resp_symp</code> indicates the number of respiratory symptoms
of each case.</p>
<pre class="r"><code>df &lt;- select(data,dyspnea,fatigue,saturation,resp_dist )
soma &lt;- function(x){
  if (sum(is.na(x))==4)
    return(NA_character_)
  else
   return(sum(!is.na(x) &amp; x==&quot;yes&quot;)) 
}
data$qt_sintomas_resp_aux &lt;- apply(df,1,soma)

data &lt;-  data %&gt;%
  mutate(resp_symp = case_when(qt_sintomas_resp_aux &gt;=1 ~ &quot;yes&quot;,
                                  qt_sintomas_resp_aux ==0 ~ &quot;no&quot;,
                               TRUE ~ NA_character_))

with(data, ctable(CVD, resp_symp, prop=&quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * resp_symp  
## Data Frame: data  
## 
## 
## ------- ----------- -------------- -------------- ---------------
##           resp_symp             no            yes           Total
##     CVD                                                          
##      no                935 (31.9%)   1992 (68.1%)   2927 (100.0%)
##     yes                 94 (16.3%)    484 (83.7%)    578 (100.0%)
##   Total               1029 (29.4%)   2476 (70.6%)   3505 (100.0%)
## ------- ----------- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    56.4759     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.42        1.91       3.05   
## ----------------------------------</code></pre>
<pre class="r"><code>data &lt;-  data %&gt;%
  mutate(qt_resp_symp = case_when(qt_sintomas_resp_aux == 4  ~ &quot;4 symptoms&quot;,
                                  qt_sintomas_resp_aux == 3  ~ &quot;3 symptoms&quot;,
                                  qt_sintomas_resp_aux == 2  ~ &quot;2 symptoms&quot;,
                                  qt_sintomas_resp_aux == 1  ~ &quot;1 symptom&quot;,
                                  qt_sintomas_resp_aux == 0  ~ &quot;No respiratory symptom&quot;,
                               TRUE ~ NA_character_))

with(data, ctable(qt_resp_symp, CVD, prop=&quot;c&quot;, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## qt_resp_symp * CVD  
## Data Frame: data  
## 
## 
## ------------------------ ----- --------------- -------------- ---------------
##                            CVD              no            yes           Total
##             qt_resp_symp                                                     
##                1 symptom          640 ( 21.9%)   116 ( 20.1%)    756 ( 21.6%)
##               2 symptoms          528 ( 18.0%)   151 ( 26.1%)    679 ( 19.4%)
##               3 symptoms          615 ( 21.0%)   164 ( 28.4%)    779 ( 22.2%)
##               4 symptoms          209 (  7.1%)    53 (  9.2%)    262 (  7.5%)
##   No respiratory symptom          935 ( 31.9%)    94 ( 16.3%)   1029 ( 29.4%)
##                    Total         2927 (100.0%)   578 (100.0%)   3505 (100.0%)
## ------------------------ ----- --------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    71.8703     4       0    
## ----------------------------</code></pre>
</div>
<div id="any-symptom" class="section level2">
<h2>Any symptom</h2>
<!-- Similar to the analysis of any respiratory symptom, we are going to create the variable `symp` indicating the presence of at least one symptom (Dyspnea, Fatigue, Saturation, Respiratory distress, Fever, Cough, Sore throat, Diarrhea, Vomit, Abdominal pain, Loss of smell, Loss of taste). Empty cells are considered missing data (`<NA>`). -->
<pre class="r"><code>df &lt;- select(data, dyspnea, fatigue, saturation, resp_dist, fever, cough, sore_throat, diarrhea, vomit, abd_pain, loss_smell,loss_taste)

soma &lt;- function(x){
  if (sum(is.na(x)) == 12)
    return(NA_character_)
  else
    return(sum(!is.na(x) &amp; x==&quot;yes&quot;)) 
}
data$qt_symp_aux &lt;- apply(df,1,soma)

data &lt;-  data %&gt;%
  mutate(symp = case_when(qt_symp_aux &gt;= 1 ~ &quot;yes&quot;,
                          qt_symp_aux == 0 ~ &quot;no&quot;,
                          TRUE ~ NA_character_))

with(data, ctable(CVD, symp,  prop=&quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * symp  
## Data Frame: data  
## 
## 
## ------- ------ ------------ -------------- ---------------
##           symp           no            yes           Total
##     CVD                                                   
##      no          256 (8.7%)   2685 (91.3%)   2941 (100.0%)
##     yes           22 (3.7%)    574 (96.3%)    596 (100.0%)
##   Total          278 (7.9%)   3259 (92.1%)   3537 (100.0%)
## ------- ------ ------------ -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    16.513      1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.49        1.59       3.88   
## ----------------------------------</code></pre>
</div>
</div>
<div id="comorbities" class="section level1">
<h1>Comorbities</h1>
<pre class="r"><code>#Hematologic
data &lt;-  data %&gt;%
mutate(hematologic = case_when(HEMATOLOGI == 1 ~ &quot;yes&quot;,
                              HEMATOLOGI == 2 ~ &quot;no&quot;, 
                              TRUE ~ NA_character_))
#Immunodepression
data &lt;-  data %&gt;%
mutate(imunodepre = case_when(IMUNODEPRE == 1 ~ &quot;yes&quot;,
                              IMUNODEPRE == 2 ~ &quot;no&quot;, 
                              TRUE ~ NA_character_))
#Hepatic
data &lt;-  data %&gt;%
mutate(hepatic = case_when(HEPATICA == 1 ~ &quot;yes&quot;,
                            HEPATICA== 2 ~ &quot;no&quot;, 
                            TRUE ~ NA_character_))
#Asthma
data &lt;-  data %&gt;%
mutate(asthma = case_when(ASMA == 1 ~ &quot;yes&quot;,
                        ASMA == 2 ~ &quot;no&quot;, 
                        TRUE ~ NA_character_))
#Diabetes
data &lt;-  data %&gt;%
mutate(diabetes = case_when(DIABETES == 1 ~ &quot;yes&quot;,
                            DIABETES == 2 ~ &quot;no&quot;, 
                            TRUE ~ NA_character_))
#Neurologic
data &lt;-  data %&gt;%
mutate(neurologic = case_when(NEUROLOGIC == 1 ~ &quot;yes&quot;,
                              NEUROLOGIC == 2 ~ &quot;no&quot;, 
                              TRUE ~ NA_character_))
#Pneumologic
data &lt;-  data %&gt;%
mutate(pneumologic = case_when(PNEUMOPATI == 1 ~ &quot;yes&quot;,
                              PNEUMOPATI == 2 ~ &quot;no&quot;, 
                              TRUE ~ NA_character_))
#Renal
data &lt;-  data %&gt;%
mutate(renal = case_when(RENAL == 1 ~ &quot;yes&quot;,
                         RENAL == 2 ~ &quot;no&quot;, 
                         TRUE ~ NA_character_))
#Obesity
data &lt;-  data %&gt;%
mutate(obesity = case_when(OBESIDADE == 1 ~ &quot;yes&quot;,
                              OBESIDADE == 2 ~ &quot;no&quot;, 
                              TRUE ~ NA_character_))</code></pre>
<div id="hematologic" class="section level2">
<h2>Hematologic</h2>
<pre class="r"><code>with(data, ctable(CVD, hematologic, prop = &quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR=TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * hematologic  
## Data Frame: data  
## 
## 
## ------- ------------- -------------- ----------- ---------------
##           hematologic             no         yes           Total
##     CVD                                                         
##      no                 2919 (98.9%)   31 (1.1%)   2950 (100.0%)
##     yes                  428 (97.9%)    9 (2.1%)    437 (100.0%)
##   Total                 3347 (98.8%)   40 (1.2%)   3387 (100.0%)
## ------- ------------- -------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.5101      1    0.1131  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.98        0.94       4.19   
## ----------------------------------</code></pre>
</div>
<div id="diabetes" class="section level2">
<h2>Diabetes</h2>
<pre class="r"><code>ctable(data$CVD, data$diabetes, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * diabetes  
## Data Frame: data  
## 
## 
## ------- ---------- -------------- ------------- ---------------
##           diabetes             no           yes           Total
##     CVD                                                        
##      no              2610 (88.6%)   337 (11.4%)   2947 (100.0%)
##     yes               312 (66.4%)   158 (33.6%)    470 (100.0%)
##   Total              2922 (85.5%)   495 (14.5%)   3417 (100.0%)
## ------- ---------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##   159.2143     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     3.92        3.14       4.90   
## ----------------------------------</code></pre>
</div>
<div id="obesity" class="section level2">
<h2>Obesity</h2>
<pre class="r"><code>ctable(data$CVD, data$obesity, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * obesity  
## Data Frame: data  
## 
## 
## ------- --------- -------------- ------------- ---------------
##           obesity             no           yes           Total
##     CVD                                                       
##      no             2651 (91.2%)   255 ( 8.8%)   2906 (100.0%)
##     yes              344 (76.6%)   105 (23.4%)    449 (100.0%)
##   Total             2995 (89.3%)   360 (10.7%)   3355 (100.0%)
## ------- --------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    85.149      1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     3.17        2.46       4.09   
## ----------------------------------</code></pre>
</div>
<div id="asthma" class="section level2">
<h2>Asthma</h2>
<pre class="r"><code>ctable(data$CVD, data$asthma, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * asthma  
## Data Frame: data  
## 
## 
## ------- -------- -------------- ------------ ---------------
##           asthma             no          yes           Total
##     CVD                                                     
##      no            2734 (93.2%)   199 (6.8%)   2933 (100.0%)
##     yes             396 (90.8%)    40 (9.2%)    436 (100.0%)
##   Total            3130 (92.9%)   239 (7.1%)   3369 (100.0%)
## ------- -------- -------------- ------------ ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.9356      1    0.0866  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.39        0.97       1.98   
## ----------------------------------</code></pre>
</div>
<div id="hepatic" class="section level2">
<h2>Hepatic</h2>
<pre class="r"><code>ctable(data$CVD, data$hepatic, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * hepatic  
## Data Frame: data  
## 
## 
## ------- --------- --------------- ----------- ---------------
##           hepatic              no         yes           Total
##     CVD                                                      
##      no             2921 ( 99.6%)   12 (0.4%)   2933 (100.0%)
##     yes              426 ( 98.8%)    5 (1.2%)    431 (100.0%)
##   Total             3347 ( 99.5%)   17 (0.5%)   3364 (100.0%)
## ------- --------- --------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.8535      1    0.0912  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.86        1.00       8.15   
## ----------------------------------</code></pre>
<pre class="r"><code>fisher.test(data$hepatic, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$hepatic and data$CVD
## p-value = 0.05627
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.7841874 8.7612195
## sample estimates:
## odds ratio 
##   2.855734</code></pre>
</div>
<div id="neurologic" class="section level2">
<h2>Neurologic</h2>
<pre class="r"><code>ctable(data$CVD, data$neurologic, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * neurologic  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- ----------- ---------------
##           neurologic             no         yes           Total
##     CVD                                                        
##      no                2915 (99.0%)   28 (1.0%)   2943 (100.0%)
##     yes                 422 (97.9%)    9 (2.1%)    431 (100.0%)
##   Total                3337 (98.9%)   37 (1.1%)   3374 (100.0%)
## ------- ------------ -------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.4923      1    0.0617  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.22        1.04       4.74   
## ----------------------------------</code></pre>
<pre class="r"><code>fisher.test(data$neurologic, data$CVD)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  data$neurologic and data$CVD
## p-value = 0.04511
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.9148775 4.8799321
## sample estimates:
## odds ratio 
##   2.219605</code></pre>
</div>
<div id="pneumologic" class="section level2">
<h2>Pneumologic</h2>
<pre class="r"><code>ctable(data$CVD, data$pneumologic, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * pneumologic  
## Data Frame: data  
## 
## 
## ------- ------------- -------------- ----------- ---------------
##           pneumologic             no         yes           Total
##     CVD                                                         
##      no                 2905 (98.9%)   31 (1.1%)   2936 (100.0%)
##     yes                  424 (97.0%)   13 (3.0%)    437 (100.0%)
##   Total                 3329 (98.7%)   44 (1.3%)   3373 (100.0%)
## ------- ------------- -------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    9.4404      1    0.0021  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.87        1.49       5.53   
## ----------------------------------</code></pre>
</div>
<div id="immunodepression" class="section level2">
<h2>Immunodepression</h2>
<pre class="r"><code>ctable(data$CVD, data$imunodepre, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * imunodepre  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- ----------- ---------------
##           imunodepre             no         yes           Total
##     CVD                                                        
##      no                2874 (98.0%)   58 (2.0%)   2932 (100.0%)
##     yes                 418 (96.5%)   15 (3.5%)    433 (100.0%)
##   Total                3292 (97.8%)   73 (2.2%)   3365 (100.0%)
## ------- ------------ -------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.2567      1    0.0711  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.78        1.00       3.17   
## ----------------------------------</code></pre>
</div>
<div id="renal" class="section level2">
<h2>Renal</h2>
<pre class="r"><code>ctable(data$CVD, data$renal, chisq=TRUE, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * renal  
## Data Frame: data  
## 
## 
## ------- ------- -------------- ----------- ---------------
##           renal             no         yes           Total
##     CVD                                                   
##      no           2890 (98.8%)   36 (1.2%)   2926 (100.0%)
##     yes            414 (95.6%)   19 (4.4%)    433 (100.0%)
##   Total           3304 (98.4%)   55 (1.6%)   3359 (100.0%)
## ------- ------- -------------- ----------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    21.431      1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     3.68        2.09       6.48   
## ----------------------------------</code></pre>
<p>The variable <code>comorb_group</code> indicates the number o
comorbidities of each notification.</p>
</div>
<div id="any-comorbidity" class="section level2">
<h2>Any comorbidity</h2>
<pre class="r"><code>df &lt;- select(data,obesity,hematologic,hepatic,asthma,diabetes,neurologic,pneumologic,imunodepre,renal)
soma &lt;- function(x){
  if (sum(is.na(x))==9)
    return(NA_character_)
  else
   return(sum(!is.na(x) &amp; x==&quot;yes&quot;)) 
}
data$qt_comorb_aux &lt;- apply(df,1,soma)

data &lt;-  data %&gt;%
  mutate(qt_comorb = case_when(qt_comorb_aux== 9  ~ &quot;9 comorbidities&quot;,                                                                           qt_comorb_aux== 8  ~ &quot;8 comorbidities&quot;,
                                  qt_comorb_aux == 7  ~ &quot;7 comorbidities&quot;,
                                  qt_comorb_aux== 6  ~ &quot;6 comorbidities&quot;,
                                  qt_comorb_aux == 5  ~ &quot;5 comorbidities&quot;,
                                  qt_comorb_aux== 4  ~ &quot;4 comorbidities&quot;,
                                  qt_comorb_aux == 3  ~ &quot;3 comorbidities&quot;,
                                  qt_comorb_aux == 2  ~ &quot;2 comorbidities&quot;,
                                  qt_comorb_aux == 1  ~ &quot;1 comorbidity&quot;,
                                  qt_comorb_aux == 0  ~ &quot;No comorbidity&quot;,
                               TRUE ~ NA_character_))

data &lt;-  data %&gt;%
  mutate(comorb_group = case_when(qt_comorb_aux == 0 ~ &quot;No comorbidity&quot;,
                                  qt_comorb_aux == 1 ~ &quot;1 comorbidity&quot;,
                                  qt_comorb_aux == 2 ~ &quot;2 comorbidities&quot;,
                                  qt_comorb_aux &gt; 2 ~ &quot;&gt;2 comorbidities&quot;,
                                  TRUE ~ NA_character_))

data$comorb_group &lt;-
  factor(data$comorb_group, levels = c(&quot;No comorbidity&quot;, &quot;1 comorbidity&quot;, &quot;2 comorbidities&quot;, &quot;&gt;2 comorbidities&quot;))</code></pre>
<pre class="r"><code>with(data, ctable(comorb_group, CVD, prop=&quot;c&quot;, useNA = &quot;no&quot;, chisq = TRUE, OR = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## comorb_group * CVD  
## Data Frame: data  
## 
## 
## ------------------ ----- --------------- -------------- ---------------
##                      CVD              no            yes           Total
##       comorb_group                                                     
##     No comorbidity         2126 ( 71.8%)   234 ( 46.8%)   2360 ( 68.2%)
##      1 comorbidity          701 ( 23.7%)   186 ( 37.2%)    887 ( 25.6%)
##    2 comorbidities          116 (  3.9%)    64 ( 12.8%)    180 (  5.2%)
##   &gt;2 comorbidities           17 (  0.6%)    16 (  3.2%)     33 (  1.0%)
##              Total         2960 (100.0%)   500 (100.0%)   3460 (100.0%)
## ------------------ ----- --------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##   165.5306     3       0    
## ----------------------------</code></pre>
</div>
</div>
<div id="outcome" class="section level1">
<h1>Outcome</h1>
<pre class="r"><code># ICU
data &lt;-  data %&gt;%
  mutate(icu = case_when(UTI == 1 ~ &quot;yes&quot;,
                         UTI == 2 ~ &quot;no&quot;,
                         TRUE ~ NA_character_))

# Ventilatory support
data &lt;-  data %&gt;%
  mutate(ven_support = case_when(SUPORT_VEN == 1 ~ &quot;yes, invasive&quot;,
                                SUPORT_VEN == 2 ~ &quot;yes, noninvasive&quot;,
                                SUPORT_VEN == 3 ~ &quot;No&quot;,
                               TRUE ~ NA_character_))</code></pre>
<div id="icu" class="section level2">
<h2>ICU</h2>
<pre class="r"><code>#tabela cruzada de uti 
with(data, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: data  
## 
## 
## ------- ----- -------------- -------------- ---------------
##           icu             no            yes           Total
##     CVD                                                    
##      no         2043 (71.8%)    802 (28.2%)   2845 (100.0%)
##     yes          356 (63.0%)    209 (37.0%)    565 (100.0%)
##   Total         2399 (70.4%)   1011 (29.6%)   3410 (100.0%)
## ------- ----- -------------- -------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    17.0872     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.50        1.24       1.81   
## ----------------------------------</code></pre>
<div id="st-trimester" class="section level3">
<h3>1st trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df4, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df4  
## 
## 
## ------- ----- ------------- ------------ --------------
##           icu            no          yes          Total
##     CVD                                                
##      no         121 (77.1%)   36 (22.9%)   157 (100.0%)
##     yes          18 (58.1%)   13 (41.9%)    31 (100.0%)
##   Total         139 (73.9%)   49 (26.1%)   188 (100.0%)
## ------- ----- ------------- ------------ --------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.9164      1    0.0478  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.43        1.09       5.43   
## ----------------------------------</code></pre>
</div>
<div id="nd-trimester" class="section level3">
<h3>2nd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df4, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df4  
## 
## 
## ------- ----- ------------- ------------- --------------
##           icu            no           yes          Total
##     CVD                                                 
##      no         315 (68.8%)   143 (31.2%)   458 (100.0%)
##     yes          66 (58.4%)    47 (41.6%)   113 (100.0%)
##   Total         381 (66.7%)   190 (33.3%)   571 (100.0%)
## ------- ----- ------------- ------------- --------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.9355      1    0.0473  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.57        1.03       2.39   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester" class="section level3">
<h3>3rd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df4, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df4  
## 
## 
## ------- ----- -------------- ------------- ---------------
##           icu             no           yes           Total
##     CVD                                                   
##      no          883 (76.6%)   270 (23.4%)   1153 (100.0%)
##     yes          159 (68.2%)    74 (31.8%)    233 (100.0%)
##   Total         1042 (75.2%)   344 (24.8%)   1386 (100.0%)
## ------- ----- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    6.7894      1    0.0092  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.52        1.12       2.07   
## ----------------------------------</code></pre>
</div>
<div id="puerperium" class="section level3">
<h3>Puerperium</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df4, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df4  
## 
## 
## ------- ----- ------------- ------------- ---------------
##           icu            no           yes           Total
##     CVD                                                  
##      no         678 (66.9%)   335 (33.1%)   1013 (100.0%)
##     yes          94 (58.4%)    67 (41.6%)    161 (100.0%)
##   Total         772 (65.8%)   402 (34.2%)   1174 (100.0%)
## ------- ----- ------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    4.1332      1     0.042  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.44        1.03       2.03   
## ----------------------------------</code></pre>
</div>
</div>
<div id="duration-of-hospitalization-in-icu" class="section level2">
<h2>Duration of hospitalization in ICU</h2>
<pre class="r"><code>data &lt;- data %&gt;%
   dplyr::mutate(
    dt_entuti = as.Date(DT_ENTUTI, format = &quot;%d/%m/%Y&quot;),
    dt_saiduti = as.Date(DT_SAIDUTI, format = &quot;%d/%m/%Y&quot;),
    icu_days = as.numeric(dt_saiduti-dt_entuti)
)</code></pre>
<pre class="r"><code>df &lt;- data[data$icu== &quot;yes&quot; &amp; !is.na(data$icu) &amp; !is.na(data$icu_days),]

datasummary((CVD) ~ icu_days*(n+media+DP+mediana+minimo+maximo+q25+q75+IQR),
            data = df, output = &#39;markdown&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">CVD</th>
<th align="right">n</th>
<th align="right">media</th>
<th align="right">DP</th>
<th align="right">mediana</th>
<th align="right">minimo</th>
<th align="right">maximo</th>
<th align="right">q25</th>
<th align="right">q75</th>
<th align="right">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">514</td>
<td align="right">10.53</td>
<td align="right">10.73</td>
<td align="right">7.00</td>
<td align="right">0.00</td>
<td align="right">94.00</td>
<td align="right">3.00</td>
<td align="right">15.00</td>
<td align="right">12.00</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">114</td>
<td align="right">13.46</td>
<td align="right">14.49</td>
<td align="right">10.50</td>
<td align="right">0.00</td>
<td align="right">105.00</td>
<td align="right">4.00</td>
<td align="right">17.00</td>
<td align="right">13.00</td>
</tr>
</tbody>
</table>
<pre class="r"><code>wilcox.test(icu_days ~ CVD, data = df)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  icu_days by CVD
## W = 25486, p-value = 0.02941
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="ventilatory-support" class="section level2">
<h2>Ventilatory support</h2>
<pre class="r"><code>with(data, ctable(CVD, ven_support, prop=&quot;r&quot;, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * ven_support  
## Data Frame: data  
## 
## 
## ------- ------------- -------------- --------------- ------------------ ---------------
##           ven_support             No   yes, invasive   yes, noninvasive           Total
##     CVD                                                                                
##      no                 1470 (52.7%)     443 (15.9%)        877 (31.4%)   2790 (100.0%)
##     yes                  226 (40.7%)     110 (19.8%)        219 (39.5%)    555 (100.0%)
##   Total                 1696 (50.7%)     553 (16.5%)       1096 (32.8%)   3345 (100.0%)
## ------- ------------- -------------- --------------- ------------------ ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    26.5268     2       0    
## ----------------------------</code></pre>
</div>
<div id="intubation" class="section level2">
<h2>Intubation</h2>
<pre class="r"><code>data &lt;- data %&gt;% 
  mutate(intubation = case_when(SUPORT_VEN == 1 ~ &quot;yes&quot;,
                                SUPORT_VEN == 2 ~ &quot;no&quot;,
                                SUPORT_VEN == 3 ~ &quot;no&quot;,
                               TRUE ~ NA_character_)
         )</code></pre>
<pre class="r"><code>with(data, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: data  
## 
## 
## ------- ------------ -------------- ------------- ---------------
##           intubation             no           yes           Total
##     CVD                                                          
##      no                2347 (84.1%)   443 (15.9%)   2790 (100.0%)
##     yes                 445 (80.2%)   110 (19.8%)    555 (100.0%)
##   Total                2792 (83.5%)   553 (16.5%)   3345 (100.0%)
## ------- ------------ -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    4.9304      1    0.0264  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.31        1.04       1.65   
## ----------------------------------</code></pre>
<div id="st-trimester-1" class="section level3">
<h3>1st trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ ------------- ------------ --------------
##           intubation            no          yes          Total
##     CVD                                                       
##      no                135 (88.8%)   17 (11.2%)   152 (100.0%)
##     yes                 23 (79.3%)    6 (20.7%)    29 (100.0%)
##   Total                158 (87.3%)   23 (12.7%)   181 (100.0%)
## ------- ------------ ------------- ------------ --------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.07        0.74       5.80   
## ----------------------------------</code></pre>
<pre class="r"><code>fisher.test(df4$CVD, df4$intubation)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  df4$CVD and df4$intubation
## p-value = 0.2182
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.601484 6.248095
## sample estimates:
## odds ratio 
##   2.061721</code></pre>
</div>
<div id="nd-trimester-1" class="section level3">
<h3>2nd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ ------------- ------------ --------------
##           intubation            no          yes          Total
##     CVD                                                       
##      no                373 (85.0%)   66 (15.0%)   439 (100.0%)
##     yes                 88 (79.3%)   23 (20.7%)   111 (100.0%)
##   Total                461 (83.8%)   89 (16.2%)   550 (100.0%)
## ------- ------------ ------------- ------------ --------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.7139      1    0.1905  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.48        0.87       2.51   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester-1" class="section level3">
<h3>3rd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ -------------- ------------- ---------------
##           intubation             no           yes           Total
##     CVD                                                          
##      no                1007 (89.0%)   125 (11.0%)   1132 (100.0%)
##     yes                 195 (84.4%)    36 (15.6%)    231 (100.0%)
##   Total                1202 (88.2%)   161 (11.8%)   1363 (100.0%)
## ------- ------------ -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.3759      1    0.0662  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.49        1.00       2.22   
## ----------------------------------</code></pre>
</div>
<div id="puerperium-1" class="section level3">
<h3>Puerperium</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ ------------- ------------- ---------------
##           intubation            no           yes           Total
##     CVD                                                         
##      no                778 (77.6%)   224 (22.4%)   1002 (100.0%)
##     yes                118 (75.2%)    39 (24.8%)    157 (100.0%)
##   Total                896 (77.3%)   263 (22.7%)   1159 (100.0%)
## ------- ------------ ------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    0.3468      1    0.5559  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.15        0.78       1.70   
## ----------------------------------</code></pre>
</div>
</div>
<div id="outcome---cure-x-death" class="section level2">
<h2>Outcome - cure x death</h2>
<pre class="r"><code>with(data, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: data  
## 
## 
## ------- ----------- -------------- ------------- ---------------
##           evolution           cure         death           Total
##     CVD                                                         
##      no               2559 (86.5%)   401 (13.5%)   2960 (100.0%)
##     yes                488 (81.1%)   114 (18.9%)    602 (100.0%)
##   Total               3047 (85.5%)   515 (14.5%)   3562 (100.0%)
## ------- ----------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    11.3176     1     8e-04  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.49        1.19       1.88   
## ----------------------------------</code></pre>
<div id="st-trimester-2" class="section level3">
<h3>1st trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = FALSE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- ------------- ------------ --------------
##           evolution          cure        death          Total
##     CVD                                                      
##      no               146 (90.7%)   15 ( 9.3%)   161 (100.0%)
##     yes                30 (88.2%)    4 (11.8%)    34 (100.0%)
##   Total               176 (90.3%)   19 ( 9.7%)   195 (100.0%)
## ------- ----------- ------------- ------------ --------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.30        0.40       4.18   
## ----------------------------------</code></pre>
<pre class="r"><code>fisher.test(df4$CVD, df4$evolution)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  df4$CVD and df4$evolution
## p-value = 0.7494
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.2926084 4.4639958
## sample estimates:
## odds ratio 
##   1.295924</code></pre>
</div>
<div id="nd-trimester-2" class="section level3">
<h3>2nd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- ------------- ------------ --------------
##           evolution          cure        death          Total
##     CVD                                                      
##      no               410 (87.0%)   61 (13.0%)   471 (100.0%)
##     yes                90 (75.0%)   30 (25.0%)   120 (100.0%)
##   Total               500 (84.6%)   91 (15.4%)   591 (100.0%)
## ------- ----------- ------------- ------------ --------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##     9.753      1    0.0018  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.24        1.37       3.67   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester-2" class="section level3">
<h3>3rd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- -------------- ------------- ---------------
##           evolution           cure         death           Total
##     CVD                                                         
##      no               1071 (89.3%)   128 (10.7%)   1199 (100.0%)
##     yes                212 (85.5%)    36 (14.5%)    248 (100.0%)
##   Total               1283 (88.7%)   164 (11.3%)   1447 (100.0%)
## ------- ----------- -------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.6461      1    0.1038  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.42        0.95       2.12   
## ----------------------------------</code></pre>
</div>
<div id="puerperium-2" class="section level3">
<h3>Puerperium</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- ------------- ------------- ---------------
##           evolution          cure         death           Total
##     CVD                                                        
##      no               856 (81.9%)   189 (18.1%)   1045 (100.0%)
##     yes               133 (78.2%)    37 (21.8%)    170 (100.0%)
##   Total               989 (81.4%)   226 (18.6%)   1215 (100.0%)
## ------- ----------- ------------- ------------- ---------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.0751      1    0.2998  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.26        0.85       1.87   
## ----------------------------------</code></pre>
</div>
</div>
<div
id="time-elapsed-between-the-start-of-symptoms-and-the-outcome-days"
class="section level2">
<h2>Time elapsed between the start of symptoms and the outcome
(days)</h2>
<pre class="r"><code>data &lt;- data %&gt;%
   dplyr::mutate(
    dt_sin_pri = as.Date(DT_SIN_PRI, format = &quot;%d/%m/%Y&quot;),
    dt_evoluca = as.Date(DT_EVOLUCA, format = &quot;%d/%m/%Y&quot;),
    days_symp_evol = as.numeric(dt_evoluca-dt_sin_pri)
)</code></pre>
<pre class="r"><code>df &lt;- data[!is.na(data$days_symp_evol) &amp; !is.na(data$CVD),]

datasummary((CVD) ~ days_symp_evol*(n+media+DP+mediana+minimo+maximo+q25+q75+IQR),
            data = df, output = &#39;markdown&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">CVD</th>
<th align="right">n</th>
<th align="right">media</th>
<th align="right">DP</th>
<th align="right">mediana</th>
<th align="right">minimo</th>
<th align="right">maximo</th>
<th align="right">q25</th>
<th align="right">q75</th>
<th align="right">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">2863</td>
<td align="right">16.00</td>
<td align="right">15.80</td>
<td align="right">13.00</td>
<td align="right">0.00</td>
<td align="right">244.00</td>
<td align="right">8.00</td>
<td align="right">19.00</td>
<td align="right">11.00</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">586</td>
<td align="right">17.10</td>
<td align="right">12.80</td>
<td align="right">14.00</td>
<td align="right">0.00</td>
<td align="right">113.00</td>
<td align="right">9.00</td>
<td align="right">20.75</td>
<td align="right">11.75</td>
</tr>
</tbody>
</table>
<pre class="r"><code>wilcox.test(days_symp_evol ~ CVD, data = df)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  days_symp_evol by CVD
## W = 751451, p-value = 6.809e-05
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<div id="considering-only-death-cases" class="section level3">
<h3>Considering only death cases</h3>
<pre class="r"><code>df &lt;- data[!is.na(data$days_symp_evol) &amp; !is.na(data$CVD),]

df &lt;- df %&gt;% 
  filter(evolution == &quot;death&quot;)

datasummary((CVD) ~ days_symp_evol*(n+media+DP+mediana+minimo+maximo+q25+q75+IQR),
            data = df, output = &#39;markdown&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">CVD</th>
<th align="right">n</th>
<th align="right">media</th>
<th align="right">DP</th>
<th align="right">mediana</th>
<th align="right">minimo</th>
<th align="right">maximo</th>
<th align="right">q25</th>
<th align="right">q75</th>
<th align="right">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">399</td>
<td align="right">20.34</td>
<td align="right">13.86</td>
<td align="right">18.00</td>
<td align="right">0.00</td>
<td align="right">158.00</td>
<td align="right">12.00</td>
<td align="right">27.00</td>
<td align="right">15.00</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">114</td>
<td align="right">20.04</td>
<td align="right">14.11</td>
<td align="right">17.00</td>
<td align="right">0.00</td>
<td align="right">113.00</td>
<td align="right">11.00</td>
<td align="right">26.75</td>
<td align="right">15.75</td>
</tr>
</tbody>
</table>
<pre class="r"><code>wilcox.test(days_symp_evol ~ CVD, data = df)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  days_symp_evol by CVD
## W = 23410, p-value = 0.6331
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="considering-only-cure-cases" class="section level3">
<h3>Considering only cure cases</h3>
<pre class="r"><code>df &lt;- data[!is.na(data$days_symp_evol) &amp; !is.na(data$CVD),]

df &lt;- df %&gt;% 
  filter(evolution == &quot;cure&quot;)

datasummary((CVD) ~ days_symp_evol*(n+media+DP+mediana+minimo+maximo+q25+q75+IQR),
            data = df, output = &#39;markdown&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">CVD</th>
<th align="right">n</th>
<th align="right">media</th>
<th align="right">DP</th>
<th align="right">mediana</th>
<th align="right">minimo</th>
<th align="right">maximo</th>
<th align="right">q25</th>
<th align="right">q75</th>
<th align="right">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no</td>
<td align="right">2464</td>
<td align="right">15.30</td>
<td align="right">15.99</td>
<td align="right">12.00</td>
<td align="right">0.00</td>
<td align="right">244.00</td>
<td align="right">7.00</td>
<td align="right">18.00</td>
<td align="right">11.00</td>
</tr>
<tr class="even">
<td align="left">yes</td>
<td align="right">472</td>
<td align="right">16.39</td>
<td align="right">12.37</td>
<td align="right">13.00</td>
<td align="right">0.00</td>
<td align="right">93.00</td>
<td align="right">9.00</td>
<td align="right">19.00</td>
<td align="right">10.00</td>
</tr>
</tbody>
</table>
<pre class="r"><code>wilcox.test(days_symp_evol ~ CVD, data = df)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  days_symp_evol by CVD
## W = 513735, p-value = 5.814e-05
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div
id="distribution-of-number-of-hospitalizations-due-to-covid-19-infection-by-month-of-first-symptoms-stratified-by-groups-with-and-without-cvd"
class="section level2">
<h2>Distribution of number of hospitalizations due to COVID-19 infection
by month of first symptoms, stratified by groups with and without
CVD</h2>
<pre class="r"><code># Date of the first symptoms
data &lt;- data %&gt;%
mutate(dt_first_symp = as.Date(DT_SIN_PRI, format = &quot;%d/%m/%Y&quot;)
)</code></pre>
<p>The next graph presents the temporal evolution of hospitalizations by
month of first symptoms, stratified by groups with and without
cardiovascular disease.</p>
<pre class="r"><code>## Creating the variable month_year
d1 &lt;- data[data$dt_first_symp &lt; as.Date(&quot;01/04/2021&quot;,format=&quot;%d/%m/%Y&quot;),] 
d1 &lt;- d1 %&gt;%
mutate(month_year = paste(formatC(month(dt_first_symp), width=2, format=&quot;d&quot;, flag=&quot;0&quot;),year(dt_first_symp),sep=&quot;/&quot;))

d&lt;- table(factor(d1$month_year, levels = c(&quot;03/2020&quot;, &quot;04/2020&quot;, &quot;05/2020&quot;, &quot;06/2020&quot;, &quot;07/2020&quot;, &quot;08/2020&quot;, &quot;09/2020&quot;, &quot;10/2020&quot;, &quot;11/2020&quot;, &quot;12/2020&quot;, &quot;01/2021&quot;, &quot;02/2021&quot;, &quot;03/2021&quot;) ), d1$CVD)
G &lt;- data.table(d)
Sys.setlocale(&quot;LC_TIME&quot;,&quot;C&quot;)</code></pre>
<pre><code>## [1] &quot;C&quot;</code></pre>
<pre class="r"><code>G$V1 &lt;- as.yearmon(G$V1, format = &quot;%m/%Y&quot;)
ggplot(G, aes(x=V1, y=N, colour=factor(V2), linetype=factor(V2), group(V2))) +
  geom_line(size=1.2) + geom_point(size=7, show.legend = FALSE) + 
  geom_text(color=&quot;white&quot;, size=3, aes(label=N)) +
  # theme(legend.position=&quot;bottom&quot;, legend.box = &quot;horizontal&quot;)+
  scale_linetype_manual(values=c(&quot;twodash&quot;, &quot;solid&quot;))+
  scale_color_manual(values = c(6,4))+
  labs( x=&quot;Month of first symptom&quot;, y=&quot;Absolute frequency&quot;, linetype = &quot;CVD&quot;, color = &quot;CVD&quot;)</code></pre>
<p><img src="Report-paper_COVID-19_cardiovascular-disease_revis%C3%A3o_PO_files/figure-html/unnamed-chunk-111-1.png" width="672" /></p>
<p>Frequency table of number of hospitalizations due to COVID-19
infection by month of first symptoms, stratified by groups with and
without CVD.</p>
<pre class="r"><code>d1$mes_ano &lt;- factor(d1$month_year, levels = c(&quot;03/2020&quot;, &quot;04/2020&quot;, &quot;05/2020&quot;, &quot;06/2020&quot;, &quot;07/2020&quot;, &quot;08/2020&quot;, &quot;09/2020&quot;, &quot;10/2020&quot;, &quot;11/2020&quot;, &quot;12/2020&quot;, &quot;01/2021&quot;, &quot;02/2021&quot;, &quot;03/2021&quot;))
ctable(d1$month_year, d1$CVD, prop=&quot;c&quot;, useNA = &quot;no&quot;)</code></pre>
<pre><code>## Cross-Tabulation, Column Proportions  
## month_year * CVD  
## Data Frame: d1  
## 
## ------------ ----- --------------- -------------- ---------------
##                CVD              no            yes           Total
##   month_year                                                     
##      01/2021          190 (  6.7%)    41 (  7.0%)    231 (  6.7%)
##      02/2021          279 (  9.8%)    56 (  9.6%)    335 (  9.7%)
##      03/2020           26 (  0.9%)     9 (  1.5%)     35 (  1.0%)
##      03/2021          413 ( 14.5%)    91 ( 15.5%)    504 ( 14.7%)
##      04/2020          194 (  6.8%)    50 (  8.5%)    244 (  7.1%)
##      05/2020          325 ( 11.4%)    64 ( 10.9%)    389 ( 11.3%)
##      06/2020          324 ( 11.4%)    59 ( 10.1%)    383 ( 11.1%)
##      07/2020          342 ( 12.0%)    67 ( 11.4%)    409 ( 11.9%)
##      08/2020          192 (  6.7%)    34 (  5.8%)    226 (  6.6%)
##      09/2020          130 (  4.6%)    19 (  3.2%)    149 (  4.3%)
##      10/2020          112 (  3.9%)    19 (  3.2%)    131 (  3.8%)
##      11/2020          154 (  5.4%)    29 (  4.9%)    183 (  5.3%)
##      12/2020          171 (  6.0%)    48 (  8.2%)    219 (  6.4%)
##        Total         2852 (100.0%)   586 (100.0%)   3438 (100.0%)
## ------------ ----- --------------- -------------- ---------------</code></pre>
<p>Now, to understand better the monthly growth rate of hospitalized
cases by COVID-19, we present the following graph:</p>
<pre class="r"><code>D1&lt;- table(d1$month_year, d1$CVD) %&gt;%
      data.table()
D1$V1 &lt;- as.yearmon(D1$V1, format = &quot;%m/%Y&quot;)

# Calculating the monthly growth rate
D1 &lt;- D1 %&gt;% 
  arrange(D1)

dif&lt;-c()
dif[1:2]&lt;-0
for(i in 1:nrow(D1)){
  if( i %% 2 == 0){
    dif[i]&lt;-D1$N[i+2]-D1$N[i]
  }
  else{
    dif[i]&lt;-D1$N[i+2]-D1$N[i] 
  }
}
D1$dif&lt;-dif

taxa_cresc&lt;-c()
taxa_cresc[1:2]&lt;-0
for(i in 1:(nrow(D1)-2)){
  if( i %% 2 == 0){
    taxa_cresc[i+2]&lt;-(dif[i])/(D1$N[i])
  }
  else{
    taxa_cresc[i+2]&lt;-(dif[i])/(D1$N[i])
  }
}

D1$growth_rate &lt;-taxa_cresc*100 

ggplot(D1, aes(x=V1, y = growth_rate, color = V2, linetype=factor(V2))) + 
  geom_line(size=1.2) + geom_point(size=3, show.legend = FALSE) + 
  geom_text(size = 2.5, aes(label = round(growth_rate, 2)), vjust = c(2, 2, -1.0, -1.0, -1, 2, -1, 2, 2, -1, -1, 2, -1, 2, 2, -1, 2, -1, 2, -1, -1, 2, -1, 2, 2, -1), 
            hjust = c(1.5, -0.5, 0.5, 0, 0, 0.5, rep(0.5,20)), show.legend = FALSE) +
  #  theme(legend.position=&quot;bottom&quot;, legend.box = &quot;horizontal&quot;)+
  scale_linetype_manual(values=c(&quot;twodash&quot;, &quot;solid&quot;))+
  scale_color_manual(values = c(6,4))+
  labs( x=&quot;Month of first symptom&quot;, y=&quot;Monthly growth rate (%)&quot;, linetype = &quot;CVD&quot;, color = &quot;CVD&quot;) +
  scale_y_continuous(limits = c(-100, 700))</code></pre>
<p><img src="Report-paper_COVID-19_cardiovascular-disease_revis%C3%A3o_PO_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<p>The average growth rate of COVID-19 cases related to the CVD and
non-CVD groups in each wave of infection is calculated below. For the
first we considered the period between March to October 2020 and for the
second wave from October 2020 to April 2021.</p>
<pre class="r"><code>##############
### First wave
##############

D1_FW = D1[3:16,]

### CVD group

rate &lt;- ((D1_FW[V2==&quot;yes&quot;]$growth_rate)+100)/100
rate_CVD_FW &lt;- geometric.mean(rate)
rate_CVD_FW</code></pre>
<pre><code>## [1] 1.11265</code></pre>
<pre class="r"><code>### non-CVD group

rate &lt;- ((D1_FW[V2==&quot;no&quot;]$growth_rate)+100)/100
rate_non_CVD_FW &lt;- geometric.mean(rate)
rate_non_CVD_FW</code></pre>
<pre><code>## [1] 1.231988</code></pre>
<pre class="r"><code>###############
### Second wave
###############

D1_SW = D1[17:26,]

### CVD group

rate &lt;- ((D1_SW[V2==&quot;yes&quot;]$growth_rate)+100)/100
rate_CVD_SW &lt;- geometric.mean(rate)
rate_CVD_SW</code></pre>
<pre><code>## [1] 1.36791</code></pre>
<pre class="r"><code>### non-CVD group

rate &lt;- ((D1_SW[V2==&quot;no&quot;]$growth_rate)+100)/100
rate_non_CVD_SW &lt;- geometric.mean(rate)
rate_non_CVD_SW</code></pre>
<pre><code>## [1] 1.298214</code></pre>
<div
id="proportion-of-deaths-in-the-cvd-and-non-cvd-groups-fixed-the-month-of-the-first-symptom."
class="section level3">
<h3>Proportion of deaths in the CVD and non-CVD groups, fixed the month
of the first symptom.</h3>
<pre class="r"><code># Proportion of deaths in the group with presence of CVD
d1 &lt;- data
d1 &lt;- d1 %&gt;% 
  filter(CVD == &#39;yes&#39;)
d1 &lt;-  d1 %&gt;%
  mutate(month_year = paste(formatC(month(dt_first_symp), width=2, format=&quot;d&quot;, flag=&quot;0&quot;),year(dt_first_symp),sep=&quot;/&quot;))

d&lt;- prop.table(table(d1$month_year, d1$evolution),1)
G3 &lt;- as.data.frame(d)
G3 &lt;- G3[G3$Var2 == &quot;death&quot;,]
G3$Freq &lt;- round((G3$Freq)*100, 2)
G3$Var1 &lt;- as.yearmon(G3$Var1, format = &quot;%m/%Y&quot;) 

# Proportion of deaths in the group with absence of CVD
d2 &lt;- data
d2 &lt;- d2 %&gt;%
  filter(CVD == &#39;no&#39;)
d2 &lt;-  d2 %&gt;%
  mutate(month_year = paste(formatC(month(dt_first_symp), width=2, format=&quot;d&quot;, flag=&quot;0&quot;),year(dt_first_symp),sep=&quot;/&quot;))

d2&lt;- prop.table(table(d2$month_year, d2$evolution),1)
G32 &lt;- as.data.frame(d2)
G32 &lt;- G32[G32$Var2 == &quot;death&quot;,]
G32$Freq &lt;- round((G32$Freq)*100, 2)
G32$Var1 &lt;- as.yearmon(G32$Var1, format = &quot;%m/%Y&quot;)

# Concatening the proportion of deaths in both groups, with and without CVD
G33 &lt;- rbind(G3, G32)
cardio &lt;- c(rep(&quot;yes&quot;, nrow(G3)), rep(&quot;no&quot;, nrow(G32)))
G33 &lt;- cbind(G33, cardio)

ggplot(data=G33,aes(x = Var1, y=Freq, color = cardio, linetype=cardio)) + geom_line(size=1.2) + 
  geom_point(size=3, show.legend = FALSE) +
  geom_text(size = 3.5, aes(label = c(&quot;8/41&quot;, &quot;11/56&quot;, &quot;5/9&quot;, &quot;28/91&quot;, &quot;8/50&quot;, &quot;5/16&quot;, &quot;8/64&quot;, &quot;13/59&quot;, &quot;9/67&quot;, &quot;2/34&quot;, &quot;2/19&quot;, &quot;2/19&quot;, &quot;3/29&quot;, &quot;10/48&quot;, &quot;20/190&quot;, &quot;72/279&quot;, &quot;5/26&quot;, &quot;99/413&quot;, &quot;30/194&quot;, &quot;26/108&quot;, &quot;41/325&quot;, &quot;24/324&quot;, &quot;33/342&quot;, &quot;13/192&quot;, &quot;9/130&quot;, &quot;5/112&quot;, &quot;12/154&quot;, &quot;12/171&quot;), vjust = c(2, 2, -1.0, -1.0, -1, -1, 0, -1, -1, 2.0, -1, -1, 0.25, -1, 0.25, -1, -1, 2, 2, -1, 2, 2, -0.8, -1.5, 2, 2.0, 2.5, 1), 
                            hjust = c(0.5, 0, 0.5, 0.5, -0.1, 0.3, -0.3, 0.5, 0, 0.5, 0.5, 0.5, -0.25, 0.5, -0.25, 0.5, 0.5, 0.5, 1, 0.5, 0.9, 0.5,0.8,0.36,0.5,0.5,0.3, -0.2)), 
                            show.legend = FALSE)+
  geom_hline(yintercept = 50) +
  scale_linetype_manual(values=c(&quot;twodash&quot;, &quot;solid&quot;))+
  scale_color_manual(values = c(6,4))+
   scale_y_continuous(limits = c(0, 60)) +
  labs( x=&quot;Month of first symptom&quot;, y=&quot;Proportion of deaths (%)&quot;, color = &quot;CVD&quot;, linetype = &quot;CVD&quot;) </code></pre>
<p><img src="Report-paper_COVID-19_cardiovascular-disease_revis%C3%A3o_PO_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
</div>
</div>
<div id="propensity-score-matching-psm" class="section level2">
<h2>Propensity Score Matching (PSM):</h2>
<p>The analysis that will be made in this section aims to understand the
effect of having cardiovascular disease or not on some variables of
interest such as symptoms and outcome. In order to make the CVD and
non-CVD groups similar with respect to the distribution of some
variables that may bring confusion to the study, we will make use of the
Propensity Score Matching (PSM) technique. The variables we will control
in the analysis are: age, race, diabetes and obesity.</p>
<p>First, we present the difference result between the groups regarding
the control variables before the PSM. We consider as “balanced” the
cases with mean difference greater than 0.05. As we can see, for most
categories of control variables the groups are not balanced before the
matching.</p>
<pre class="r"><code>data$cardio &lt;- ifelse(data$CVD==&quot;yes&quot;,1,0)

bal.tab(cardio ~ NU_IDADE_N + ethnicity + diabetes + obesity, data = data, estimand = &quot;ATE&quot;, m.threshold = .05)</code></pre>
<pre><code>## Balance Measures
##                         Type Diff.Un      M.Threshold.Un
## NU_IDADE_N           Contin.  0.5949 Not Balanced, &gt;0.05
## ethnicity_black       Binary  0.0258     Balanced, &lt;0.05
## ethnicity_brown       Binary -0.0535 Not Balanced, &gt;0.05
## ethnicity_indigenous  Binary -0.0097     Balanced, &lt;0.05
## ethnicity_white       Binary  0.0429     Balanced, &lt;0.05
## ethnicity_yellow      Binary -0.0054     Balanced, &lt;0.05
## ethnicity:&lt;NA&gt;        Binary  0.0264     Balanced, &lt;0.05
## diabetes_yes          Binary  0.2218 Not Balanced, &gt;0.05
## diabetes:&lt;NA&gt;         Binary  0.2149 Not Balanced, &gt;0.05
## obesity_yes           Binary  0.1461 Not Balanced, &gt;0.05
## obesity:&lt;NA&gt;          Binary  0.2359 Not Balanced, &gt;0.05
## 
## Balance tally for mean differences
##                     count
## Balanced, &lt;0.05         5
## Not Balanced, &gt;0.05     6
## 
## Variable with the greatest mean difference
##    Variable Diff.Un      M.Threshold.Un
##  NU_IDADE_N  0.5949 Not Balanced, &gt;0.05
## 
## Sample sizes
##     Control Treated
## All    2960     602</code></pre>
<p>As one can see, all variables categories are balanced after PSM.</p>
<pre class="r"><code>## Estimating the weights of each sampling unit
fit &lt;- weightit(cardio ~ NU_IDADE_N + ethnicity + diabetes + obesity, use.mlogit = FALSE, data = data,
                  method = &quot;ps&quot;, estimand = &quot;ATE&quot;)

data$weight &lt;- fit$weights

bal.tab(fit, m.threshold = 0.05, disp.v.ratio = TRUE)</code></pre>
<pre><code>## Call
##  weightit(formula = cardio ~ NU_IDADE_N + ethnicity + diabetes + 
##     obesity, data = data, method = &quot;ps&quot;, estimand = &quot;ATE&quot;, use.mlogit = FALSE)
## 
## Balance Measures
##                          Type Diff.Adj     M.Threshold V.Ratio.Adj
## prop.score           Distance   0.0394 Balanced, &lt;0.05      1.3504
## NU_IDADE_N            Contin.   0.0041 Balanced, &lt;0.05      0.9849
## ethnicity_black        Binary  -0.0003 Balanced, &lt;0.05           .
## ethnicity_brown        Binary  -0.0088 Balanced, &lt;0.05           .
## ethnicity_indigenous   Binary   0.0056 Balanced, &lt;0.05           .
## ethnicity_white        Binary   0.0088 Balanced, &lt;0.05           .
## ethnicity_yellow       Binary  -0.0052 Balanced, &lt;0.05           .
## ethnicity:&lt;NA&gt;         Binary   0.0144 Balanced, &lt;0.05           .
## diabetes_yes           Binary  -0.0036 Balanced, &lt;0.05           .
## diabetes:&lt;NA&gt;          Binary   0.0117 Balanced, &lt;0.05           .
## obesity_yes            Binary   0.0064 Balanced, &lt;0.05           .
## obesity:&lt;NA&gt;           Binary   0.0133 Balanced, &lt;0.05           .
## 
## Balance tally for mean differences
##                     count
## Balanced, &lt;0.05        12
## Not Balanced, &gt;0.05     0
## 
## Variable with the greatest mean difference
##        Variable Diff.Adj     M.Threshold
##  ethnicity:&lt;NA&gt;   0.0144 Balanced, &lt;0.05
## 
## Effective sample sizes
##            Control Treated
## Unadjusted  2960.   602.  
## Adjusted    2332.6  331.15</code></pre>
<div id="symptom-analysis-after-psm" class="section level3">
<h3>Symptom analysis after PSM:</h3>
<div id="fever-1" class="section level4">
<h4><span style="color:blue"> Fever </span></h4>
<pre class="r"><code>with(data, ctable(CVD, fever, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * fever  
## Data Frame: data  
## 
## 
## ------- ------- ---------------- ---------------- -----------------
##           fever               no              yes             Total
##     CVD                                                            
##      no           1535.7 (44.5%)   1914.5 (55.5%)   3450.2 (100.0%)
##     yes           1510.0 (43.0%)   1997.8 (57.0%)   3507.8 (100.0%)
##   Total           3045.8 (43.8%)   3912.2 (56.2%)   6958.0 (100.0%)
## ------- ------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.4564      1    0.2275  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.06        0.97       1.17   
## ----------------------------------</code></pre>
</div>
<div id="cough-1" class="section level4">
<h4><span style="color:blue"> Cough </span></h4>
<pre class="r"><code>with(data, ctable(CVD, cough, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * cough  
## Data Frame: data  
## 
## 
## ------- ------- ---------------- ---------------- -----------------
##           cough               no              yes             Total
##     CVD                                                            
##      no           1161.8 (33.7%)   2290.8 (66.3%)   3452.6 (100.0%)
##     yes           1124.8 (32.0%)   2395.0 (68.0%)   3519.8 (100.0%)
##   Total           2286.6 (32.8%)   4685.8 (67.2%)   6972.4 (100.0%)
## ------- ------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.1957      1    0.1384  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.08        0.98       1.19   
## ----------------------------------</code></pre>
</div>
<div id="sore-throat-1" class="section level4">
<h4><span style="color:blue"> Sore throat </span></h4>
<pre class="r"><code>with(data, ctable(CVD, sore_throat, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * sore_throat  
## Data Frame: data  
## 
## 
## ------- ------------- ---------------- ---------------- -----------------
##           sore_throat               no              yes             Total
##     CVD                                                                  
##      no                 2651.6 (78.2%)    738.2 (21.8%)   3389.8 (100.0%)
##     yes                 2588.7 (76.6%)    790.8 (23.4%)   3379.6 (100.0%)
##   Total                 5240.3 (77.4%)   1529.0 (22.6%)   6769.3 (100.0%)
## ------- ------------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.4586      1    0.1169  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.10        0.98       1.23   
## ----------------------------------</code></pre>
</div>
<div id="dyspnea-1" class="section level4">
<h4><span style="color:blue"> Dyspnea </span></h4>
<pre class="r"><code>with(data, ctable(CVD, dyspnea, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * dyspnea  
## Data Frame: data  
## 
## 
## ------- --------- ---------------- ---------------- -----------------
##           dyspnea               no              yes             Total
##     CVD                                                              
##      no             1574.0 (45.6%)   1876.2 (54.4%)   3450.2 (100.0%)
##     yes             1196.9 (33.9%)   2337.6 (66.1%)   3534.4 (100.0%)
##   Total             2770.8 (39.7%)   4213.8 (60.3%)   6984.6 (100.0%)
## ------- --------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##   100.3512     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.64        1.49       1.80   
## ----------------------------------</code></pre>
</div>
<div id="respiratory-distress-1" class="section level4">
<h4><span style="color:blue"> Respiratory distress </span></h4>
<pre class="r"><code>with(data, ctable(CVD, resp_dist, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * resp_dist  
## Data Frame: data  
## 
## 
## ------- ----------- ---------------- ---------------- -----------------
##           resp_dist               no              yes             Total
##     CVD                                                                
##      no               1789.1 (52.1%)   1645.7 (47.9%)   3434.8 (100.0%)
##     yes               1578.1 (45.4%)   1900.2 (54.6%)   3478.3 (100.0%)
##   Total               3367.2 (48.7%)   3545.9 (51.3%)   6913.1 (100.0%)
## ------- ----------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    30.9549     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.31        1.19       1.44   
## ----------------------------------</code></pre>
</div>
<div id="saturation-1" class="section level4">
<h4><span style="color:blue"> Saturation </span></h4>
<pre class="r"><code>with(data, ctable(CVD, saturation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * saturation  
## Data Frame: data  
## 
## 
## ------- ------------ ---------------- ---------------- -----------------
##           saturation               no              yes             Total
##     CVD                                                                 
##      no                2164.0 (63.5%)   1241.8 (36.5%)   3405.8 (100.0%)
##     yes                1810.9 (52.3%)   1654.5 (47.7%)   3465.4 (100.0%)
##   Total                3974.9 (57.8%)   2896.3 (42.2%)   6871.2 (100.0%)
## ------- ------------ ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    89.2193     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.59        1.45       1.75   
## ----------------------------------</code></pre>
</div>
<div id="diarrhea-1" class="section level4">
<h4><span style="color:blue"> Diarrhea </span></h4>
<pre class="r"><code>with(data, ctable(CVD, diarrhea, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * diarrhea  
## Data Frame: data  
## 
## 
## ------- ---------- ---------------- --------------- -----------------
##           diarrhea               no             yes             Total
##     CVD                                                              
##      no              3021.0 (88.6%)   389.7 (11.4%)   3410.7 (100.0%)
##     yes              3002.5 (89.0%)   371.5 (11.0%)   3374.1 (100.0%)
##   Total              6023.5 (88.8%)   761.2 (11.2%)   6784.7 (100.0%)
## ------- ---------- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    0.2517      1    0.6159  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     0.96        0.82       1.12   
## ----------------------------------</code></pre>
</div>
<div id="vomit-1" class="section level4">
<h4><span style="color:blue"> Vomit </span></h4>
<pre class="r"><code>with(data, ctable(CVD, vomit, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * vomit  
## Data Frame: data  
## 
## 
## ------- ------- ---------------- --------------- -----------------
##           vomit               no             yes             Total
##     CVD                                                           
##      no           3062.7 (90.1%)   337.3 ( 9.9%)   3400.1 (100.0%)
##     yes           2998.6 (89.3%)   359.5 (10.7%)   3358.1 (100.0%)
##   Total           6061.3 (89.7%)   696.8 (10.3%)   6758.1 (100.0%)
## ------- ------- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.0397      1    0.3079  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.09        0.93       1.27   
## ----------------------------------</code></pre>
</div>
<div id="fatigue-1" class="section level4">
<h4><span style="color:blue"> Fatigue </span></h4>
<pre class="r"><code>with(data, ctable(CVD, fatigue, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * fatigue  
## Data Frame: data  
## 
## 
## ------- --------- ---------------- ---------------- -----------------
##           fatigue               no              yes             Total
##     CVD                                                              
##      no             1892.0 (76.5%)    579.8 (23.5%)   2471.8 (100.0%)
##     yes             1733.2 (74.8%)    583.8 (25.2%)   2317.0 (100.0%)
##   Total             3625.2 (75.7%)   1163.6 (24.3%)   4788.8 (100.0%)
## ------- --------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##     1.871      1    0.1714  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.10        0.96       1.25   
## ----------------------------------</code></pre>
</div>
<div id="loss-of-smell-1" class="section level4">
<h4><span style="color:blue"> Loss of smell </span></h4>
<pre class="r"><code>with(data, ctable(CVD, loss_smell, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * loss_smell  
## Data Frame: data  
## 
## 
## ------- ------------ ---------------- --------------- -----------------
##           loss_smell               no             yes             Total
##     CVD                                                                
##      no                2002.3 (81.1%)   467.5 (18.9%)   2469.8 (100.0%)
##     yes                1787.6 (77.5%)   520.4 (22.5%)   2308.0 (100.0%)
##   Total                3789.9 (79.3%)   987.9 (20.7%)   4777.7 (100.0%)
## ------- ------------ ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    9.2983      1    0.0023  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.25        1.08       1.43   
## ----------------------------------</code></pre>
</div>
<div id="loss-of-taste-1" class="section level4">
<h4><span style="color:blue"> Loss of taste </span></h4>
<pre class="r"><code>with(data, ctable(CVD, loss_taste, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * loss_taste  
## Data Frame: data  
## 
## 
## ------- ------------ ---------------- --------------- -----------------
##           loss_taste               no             yes             Total
##     CVD                                                                
##      no                2008.7 (81.5%)   455.8 (18.5%)   2464.6 (100.0%)
##     yes                1792.7 (77.6%)   518.6 (22.4%)   2311.3 (100.0%)
##   Total                3801.4 (79.6%)   974.4 (20.4%)   4775.9 (100.0%)
## ------- ------------ ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    11.1723     1     8e-04  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.27        1.11       1.47   
## ----------------------------------</code></pre>
</div>
<div id="abdominal-pain-1" class="section level4">
<h4><span style="color:blue"> Abdominal pain </span></h4>
<pre class="r"><code>with(data, ctable(CVD, abd_pain, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * abd_pain  
## Data Frame: data  
## 
## 
## ------- ---------- ---------------- -------------- -----------------
##           abd_pain               no            yes             Total
##     CVD                                                             
##      no              2243.3 (91.3%)   214.6 (8.7%)   2457.9 (100.0%)
##     yes              2102.5 (92.1%)   180.7 (7.9%)   2283.2 (100.0%)
##   Total              4345.8 (91.7%)   395.3 (8.3%)   4741.2 (100.0%)
## ------- ---------- ---------------- -------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    0.9274      1    0.3355  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     0.90        0.73       1.10   
## ----------------------------------</code></pre>
</div>
<div id="any-respiratory-symptom-1" class="section level4">
<h4>Any respiratory symptom</h4>
<p>Now we are going to create the variable <code>resp_symp</code>
indicating the presence of at least one respiratory symptom (Dyspnea,
Fadigue, Saturation, Respiratory distress). Empty cells are considered
missing data (<code>&lt;NA&gt;</code>). The variable
<code>qt_resp_symp</code> indicates the number of respiratory symptoms
of each case.</p>
<pre class="r"><code>with(data, ctable(CVD, resp_symp, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * resp_symp  
## Data Frame: data  
## 
## 
## ------- ----------- ---------------- ---------------- -----------------
##           resp_symp               no              yes             Total
##     CVD                                                                
##      no               1056.4 (30.5%)   2408.6 (69.5%)   3465.1 (100.0%)
##     yes                738.7 (20.7%)   2834.6 (79.3%)   3573.4 (100.0%)
##   Total               1795.2 (25.5%)   5243.3 (74.5%)   7038.5 (100.0%)
## ------- ----------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    88.6786     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.68        1.51       1.88   
## ----------------------------------</code></pre>
<pre class="r"><code>with(data, ctable(CVD, qt_resp_symp, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * qt_resp_symp  
## Data Frame: data  
## 
## 
## ------- -------------- ---------------- ---------------- ---------------- -------------- ------------------------ -----------------
##           qt_resp_symp        1 symptom       2 symptoms       3 symptoms     4 symptoms   No respiratory symptom             Total
##     CVD                                                                                                                            
##      no                   763.3 (22.0%)    616.1 (17.8%)    768.8 (22.2%)   260.4 (7.5%)           1056.4 (30.5%)   3465.1 (100.0%)
##     yes                   709.1 (19.8%)    892.6 (25.0%)    949.9 (26.6%)   283.0 (7.9%)            738.7 (20.7%)   3573.4 (100.0%)
##   Total                  1472.4 (20.9%)   1508.7 (21.4%)   1718.8 (24.4%)   543.3 (7.7%)           1795.2 (25.5%)   7038.5 (100.0%)
## ------- -------------- ---------------- ---------------- ---------------- -------------- ------------------------ -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##   127.2795     4       0    
## ----------------------------</code></pre>
</div>
<div id="any-symptom-1" class="section level4">
<h4>Any symptom</h4>
<p>Similar to the analysis of any respiratory symptom, we are going to
create the variable <code>symp</code> indicating the presence of at
least one symptom (Dyspnea, Fatigue, Saturation, Respiratory distress,
Fever, Cough, Sore throat, Diarrhea, Vomit, Abdominal pain, Loss of
smell, Loss of taste). Empty cells are considered missing data
(<code>&lt;NA&gt;</code>).</p>
<pre class="r"><code>with(data, ctable(CVD, symp, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * symp  
## Data Frame: data  
## 
## 
## ------- ------ -------------- ---------------- -----------------
##           symp             no              yes             Total
##     CVD                                                         
##      no          285.8 (8.2%)   3197.3 (91.8%)   3483.1 (100.0%)
##     yes          135.9 (3.8%)   3458.6 (96.2%)   3594.5 (100.0%)
##   Total          421.7 (6.0%)   6655.9 (94.0%)   7077.6 (100.0%)
## ------- ------ -------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    61.0733     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     2.28        1.85       2.81   
## ----------------------------------</code></pre>
</div>
</div>
<div id="outcome-analysis-after-psm" class="section level3">
<h3>Outcome analysis after PSM:</h3>
</div>
</div>
<div id="icu-1" class="section level2">
<h2><span style="color:blue"> ICU </span></h2>
<pre class="r"><code>with(data, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: data  
## 
## 
## ------- ----- ---------------- ---------------- -----------------
##           icu               no              yes             Total
##     CVD                                                          
##      no         2421.5 (71.6%)    959.7 (28.4%)   3381.2 (100.0%)
##     yes         2318.3 (67.5%)   1117.4 (32.5%)   3435.7 (100.0%)
##   Total         4739.9 (69.5%)   2077.1 (30.5%)   6817.0 (100.0%)
## ------- ----- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    13.5876     1     2e-04  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.22        1.10       1.35   
## ----------------------------------</code></pre>
<div id="st-trimester-3" class="section level4">
<h4><span style="color:blue"> 1st trimester </span></h4>
<pre class="r"><code>df43 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df43, ctable(CVD, icu, prop=&quot;r&quot;, useNA = &quot;no&quot;, OR=TRUE, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df43  
## 
## 
## ------- ----- --------------- -------------- ----------------
##           icu              no            yes            Total
##     CVD                                                      
##      no         137.3 (76.8%)   41.4 (23.2%)   178.7 (100.0%)
##     yes          83.2 (63.3%)   48.2 (36.7%)   131.4 (100.0%)
##   Total         220.5 (71.1%)   89.6 (28.9%)   310.2 (100.0%)
## ------- ----- --------------- -------------- ----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    6.0614      1    0.0138  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.92        1.17       3.15   
## ----------------------------------</code></pre>
</div>
<div id="nd-trimester-3" class="section level4">
<h4><span style="color:blue"> 2nd trimester </span></h4>
<pre class="r"><code>df43 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df43, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df43  
## 
## 
## ------- ----- --------------- --------------- -----------------
##           icu              no             yes             Total
##     CVD                                                        
##      no         362.9 (68.1%)   169.9 (31.9%)    532.9 (100.0%)
##     yes         377.5 (61.4%)   237.4 (38.6%)    614.9 (100.0%)
##   Total         740.4 (64.5%)   407.4 (35.5%)   1147.8 (100.0%)
## ------- ----- --------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    5.3395      1    0.0208  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.34        1.05       1.71   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester-3" class="section level4">
<h4><span style="color:blue"> 3rd trimester </span></h4>
<pre class="r"><code>df43 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df43, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df43  
## 
## 
## ------- ----- ---------------- --------------- -----------------
##           icu               no             yes             Total
##     CVD                                                         
##      no         1058.1 (76.8%)   318.8 (23.2%)   1376.8 (100.0%)
##     yes         1252.9 (74.1%)   437.2 (25.9%)   1690.1 (100.0%)
##   Total         2311.0 (75.4%)   755.9 (24.6%)   3066.9 (100.0%)
## ------- ----- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    2.8646      1    0.0905  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.16        0.98       1.37   
## ----------------------------------</code></pre>
</div>
<div id="puerperium-3" class="section level4">
<h4><span style="color:blue"> Puerperium </span></h4>
<pre class="r"><code>df43 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df43, ctable(CVD, icu, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * icu  
## Data Frame: df43  
## 
## 
## ------- ----- ---------------- --------------- -----------------
##           icu               no             yes             Total
##     CVD                                                         
##      no          802.7 (66.3%)   407.6 (33.7%)   1210.3 (100.0%)
##     yes          540.2 (60.3%)   355.7 (39.7%)    896.0 (100.0%)
##   Total         1342.9 (63.8%)   763.4 (36.2%)   2106.3 (100.0%)
## ------- ----- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    7.8264      1    0.0051  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.30        1.08       1.55   
## ----------------------------------</code></pre>
</div>
<div id="days-of-hospitalization-in-icu" class="section level3">
<h3><span style="color:blue"> Days of hospitalization in ICU
</span></h3>
<pre class="r"><code>d_yes &lt;- data %&gt;% 
   filter(CVD == &quot;yes&quot; &amp; !is.na(icu_days))
d_no &lt;- data %&gt;% 
   filter(CVD == &quot;no&quot; &amp; !is.na(icu_days))

wtd.t.test(d_yes$icu_days, d_no$icu_days, weight = d_yes$weight, weighty = d_no$weight)</code></pre>
<pre><code>## $test
## [1] &quot;Two Sample Weighted T-Test (Welch)&quot;
## 
## $coefficients
##     t.value          df     p.value 
##   1.2896729 164.5233472   0.1989742 
## 
## $additional
## Difference     Mean.x     Mean.y   Std. Err 
##   1.437357  11.941962  10.504606   1.114513</code></pre>
</div>
</div>
<div id="ventilatory-support-1" class="section level2">
<h2><span style="color:blue"> Ventilatory support </span></h2>
<pre class="r"><code>with(data, ctable(CVD, ven_support, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * ven_support  
## Data Frame: data  
## 
## 
## ------- ------------- ---------------- ---------------- ------------------ -----------------
##           ven_support               No    yes, invasive   yes, noninvasive             Total
##     CVD                                                                                     
##      no                 1693.0 (51.3%)    540.7 (16.4%)     1068.2 (32.4%)   3301.9 (100.0%)
##     yes                 1611.5 (47.2%)    603.3 (17.7%)     1197.4 (35.1%)   3412.2 (100.0%)
##   Total                 3304.6 (49.2%)   1144.0 (17.0%)     2265.6 (33.7%)   6714.2 (100.0%)
## ------- ------------- ---------------- ---------------- ------------------ -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    10.9876     2    0.0041  
## ----------------------------</code></pre>
</div>
<div id="intubation-1" class="section level2">
<h2><span style="color:blue"> Intubation </span></h2>
<pre class="r"><code>with(data, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE,  weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: data  
## 
## 
## ------- ------------ ---------------- ---------------- -----------------
##           intubation               no              yes             Total
##     CVD                                                                 
##      no                2761.2 (83.6%)    540.7 (16.4%)   3301.9 (100.0%)
##     yes                2809.0 (82.3%)    603.3 (17.7%)   3412.2 (100.0%)
##   Total                5570.2 (83.0%)   1144.0 (17.0%)   6714.2 (100.0%)
## ------- ------------ ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    1.9271      1    0.1651  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.10        0.97       1.25   
## ----------------------------------</code></pre>
<div id="st-trimester-4" class="section level3">
<h3>1st trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ --------------- -------------- ----------------
##           intubation              no            yes            Total
##     CVD                                                             
##      no                153.4 (88.7%)   19.6 (11.3%)   173.0 (100.0%)
##     yes                 97.1 (80.6%)   23.4 (19.4%)   120.5 (100.0%)
##   Total                250.5 (85.3%)   43.0 (14.7%)   293.5 (100.0%)
## ------- ------------ --------------- -------------- ----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    3.1142      1    0.0776  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.89        0.98       3.62   
## ----------------------------------</code></pre>
</div>
<div id="nd-trimester-4" class="section level3">
<h3>2nd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ --------------- --------------- -----------------
##           intubation              no             yes             Total
##     CVD                                                               
##      no                429.5 (84.4%)    79.6 (15.6%)    509.2 (100.0%)
##     yes                493.7 (81.6%)   111.4 (18.4%)    605.1 (100.0%)
##   Total                923.2 (82.9%)   191.1 (17.1%)   1114.3 (100.0%)
## ------- ------------ --------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##     1.31       1    0.2524  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.22        0.89       1.67   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester-4" class="section level3">
<h3>3rd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ ---------------- --------------- -----------------
##           intubation               no             yes             Total
##     CVD                                                                
##      no                1205.3 (89.1%)   147.2 (10.9%)   1352.5 (100.0%)
##     yes                1479.2 (86.3%)   234.6 (13.7%)   1713.7 (100.0%)
##   Total                2684.5 (87.5%)   381.8 (12.5%)   3066.3 (100.0%)
## ------- ------------ ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    5.1945      1    0.0227  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.30        1.04       1.62   
## ----------------------------------</code></pre>
</div>
<div id="puerperium-4" class="section level3">
<h3>Puerperium</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df4, ctable(CVD, intubation, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * intubation  
## Data Frame: df4  
## 
## 
## ------- ------------ ---------------- --------------- -----------------
##           intubation               no             yes             Total
##     CVD                                                                
##      no                 903.0 (76.3%)   280.6 (23.7%)   1183.6 (100.0%)
##     yes                 654.0 (75.2%)   215.5 (24.8%)    869.5 (100.0%)
##   Total                1557.0 (75.8%)   496.2 (24.2%)   2053.1 (100.0%)
## ------- ------------ ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    0.2619      1    0.6088  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.06        0.86       1.30   
## ----------------------------------</code></pre>
</div>
</div>
<div id="outcome---cure-x-death-1" class="section level2">
<h2>Outcome - cure x death</h2>
<pre class="r"><code>with(data, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: data  
## 
## 
## ------- ----------- ---------------- ---------------- -----------------
##           evolution             cure            death             Total
##     CVD                                                                
##      no               3020.3 (86.0%)    491.3 (14.0%)   3511.6 (100.0%)
##     yes               2974.7 (82.4%)    636.8 (17.6%)   3611.5 (100.0%)
##   Total               5995.0 (84.2%)   1128.1 (15.8%)   7123.1 (100.0%)
## ------- ----------- ---------------- ---------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    17.433      1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.32        1.16       1.50   
## ----------------------------------</code></pre>
<div id="st-trimester-5" class="section level3">
<h3>1st trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;1tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- --------------- -------------- ----------------
##           evolution            cure          death            Total
##     CVD                                                            
##      no               165.5 (90.4%)   17.5 ( 9.6%)   183.1 (100.0%)
##     yes               121.1 (88.1%)   16.4 (11.9%)   137.4 (100.0%)
##   Total               286.6 (89.4%)   33.9 (10.6%)   320.5 (100.0%)
## ------- ----------- --------------- -------------- ----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    0.2366      1    0.6267  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.28        0.62       2.60   
## ----------------------------------</code></pre>
</div>
<div id="nd-trimester-5" class="section level3">
<h3>2nd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;2tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- --------------- --------------- -----------------
##           evolution            cure           death             Total
##     CVD                                                              
##      no               471.8 (86.2%)    75.7 (13.8%)    547.5 (100.0%)
##     yes               484.2 (76.2%)   151.0 (23.8%)    635.3 (100.0%)
##   Total               956.0 (80.8%)   226.7 (19.2%)   1182.7 (100.0%)
## ------- ----------- --------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    18.1283     1       0    
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.94        1.43       2.63   
## ----------------------------------</code></pre>
</div>
<div id="rd-trimester-5" class="section level3">
<h3>3rd trimester</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;3tri&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- ---------------- --------------- -----------------
##           evolution             cure           death             Total
##     CVD                                                               
##      no               1279.2 (89.5%)   150.6 (10.5%)   1429.8 (100.0%)
##     yes               1565.4 (86.8%)   237.9 (13.2%)   1803.3 (100.0%)
##   Total               2844.6 (88.0%)   388.5 (12.0%)   3233.1 (100.0%)
## ------- ----------- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    5.0783      1    0.0242  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.29        1.04       1.60   
## ----------------------------------</code></pre>
</div>
<div id="puerperium-5" class="section level3">
<h3>Puerperium</h3>
<pre class="r"><code>df4 &lt;- data %&gt;% 
  filter(classi_gesta_puerp == &quot;puerp&quot;)

with(df4, ctable(CVD, evolution, prop=&quot;r&quot;, OR=TRUE, useNA = &quot;no&quot;, chisq = TRUE, weights = weight))</code></pre>
<pre><code>## Cross-Tabulation, Row Proportions  
## CVD * evolution  
## Data Frame: df4  
## 
## 
## ------- ----------- ---------------- --------------- -----------------
##           evolution             cure           death             Total
##     CVD                                                               
##      no               1009.5 (81.0%)   237.0 (19.0%)   1246.5 (100.0%)
##     yes                709.0 (77.1%)   210.6 (22.9%)    919.6 (100.0%)
##   Total               1718.5 (79.3%)   447.5 (20.7%)   2166.1 (100.0%)
## ------- ----------- ---------------- --------------- -----------------
## 
## ----------------------------
##  Chi.squared   df   p.value 
## ------------- ---- ---------
##    4.6463      1    0.0311  
## ----------------------------
## 
## ----------------------------------
##  Odds Ratio   Lo - 95%   Hi - 95% 
## ------------ ---------- ----------
##     1.27        1.03       1.56   
## ----------------------------------</code></pre>
</div>
</div>
<div
id="time-elapsed-between-the-start-of-symptoms-and-the-outcome-days-after-psm"
class="section level2">
<h2>Time elapsed between the start of symptoms and the outcome (days)
after PSM</h2>
<pre class="r"><code>d_yes &lt;- data %&gt;% 
   filter(CVD == &quot;yes&quot; &amp; !is.na(days_symp_evol))
d_no &lt;- data %&gt;% 
   filter(CVD == &quot;no&quot; &amp; !is.na(days_symp_evol))

# Performing weighted Student&#39;s t-tests to compare the CVD and non-CVD groups with respect to the time elapsed between the start of symptoms and the outcome.
wtd.t.test(d_yes$days_symp_evol, d_no$days_symp_evol, weight = d_yes$weight, weighty = d_no$weight)</code></pre>
<pre><code>## $test
## [1] &quot;Two Sample Weighted T-Test (Welch)&quot;
## 
## $coefficients
##      t.value           df      p.value 
##    0.1099694 1063.6837670    0.9124544 
## 
## $additional
##  Difference      Mean.x      Mean.y    Std. Err 
##  0.06197107 16.09992551 16.03795444  0.56353002</code></pre>
<div id="considering-only-death-cases-1" class="section level3">
<h3>Considering only death cases</h3>
<pre class="r"><code>df &lt;- data[!is.na(data$days_symp_evol) &amp; !is.na(data$CVD),]

df &lt;- df %&gt;% 
  filter(evolution == &quot;death&quot;)</code></pre>
<pre class="r"><code>d_yes &lt;- df %&gt;% 
   filter(CVD == &quot;yes&quot; &amp; !is.na(days_symp_evol))
d_no &lt;- df %&gt;% 
   filter(CVD == &quot;no&quot; &amp; !is.na(days_symp_evol))

# Fixed the death cases, we perform a weighted Student&#39;s t-tests to compare the CVD and non-CVD groups with respect to the time elipsed between the start of symptoms and the outcome.
wtd.t.test(d_yes$days_symp_evol, d_no$days_symp_evol, weight = d_yes$weight, weighty = d_no$weight)</code></pre>
<pre><code>## $test
## [1] &quot;Two Sample Weighted T-Test (Welch)&quot;
## 
## $coefficients
##     t.value          df     p.value 
##  -1.2611092 209.4593901   0.2086723 
## 
## $additional
## Difference     Mean.x     Mean.y   Std. Err 
##  -1.603168  18.525606  20.128775   1.271237</code></pre>
</div>
<div id="considering-only-cure-cases-1" class="section level3">
<h3><span style="color:blue"> Considering only cure cases </span></h3>
<pre class="r"><code>df &lt;- data[!is.na(data$days_symp_evol) &amp; !is.na(data$CVD),]

df &lt;- df %&gt;% 
  filter(evolution == &quot;cure&quot;)</code></pre>
<pre class="r"><code>d_yes &lt;- df %&gt;% 
   filter(CVD == &quot;yes&quot; &amp; !is.na(days_symp_evol))
d_no &lt;- df %&gt;% 
   filter(CVD == &quot;no&quot; &amp; !is.na(days_symp_evol))

# Fixed the cure cases, we perform a weighted Student&#39;s t-tests to compare the CVD and non-CVD groups with respect to the time elipsed between the start of symptoms and the outcome.
wtd.t.test(d_yes$days_symp_evol, d_no$days_symp_evol, weight = d_yes$weight, weighty = d_no$weight)</code></pre>
<pre><code>## $test
## [1] &quot;Two Sample Weighted T-Test (Welch)&quot;
## 
## $coefficients
##     t.value          df     p.value 
##   0.3550948 844.4701089   0.7226072 
## 
## $additional
## Difference     Mean.x     Mean.y   Std. Err 
##  0.2215880 15.5695136 15.3479256  0.6240249</code></pre>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
